---
title: "R Notebook"
---



```{r}
library(tidyverse)
source("utils.R")
source("annotation_helper.R")
library(gggroupedscale)
```

```{r}
res <-  read_tsv("../benchmark/output/benchmark_results/downsampling_best_of_results.tsv") %>% 
  transmute(benchmark = "downsampling", overlap = overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset, replicate = seed, cputime_sec = full_cputime_sec, elapsed_sec = full_elapsed_sec)%>%
  mutate(transformation = factor(transformation, levels = trans_families$transformation))
res
```

```{r}
trans_families_labels_mod <- factor(c(delta_method = "Delta\nMethod", glm_residual = "GLM\nResiduals", 
                                      latent_expr = "Latent\nExpr.", count_model = "Count\nModels"),
                                    levels = c("Count\nModels", "Latent\nExpr.", "GLM\nResiduals", "Delta\nMethod"))
```

```{r}
parameter_choices <- tibble(benchmark = "downsampling", knn = 50, pca_dim = c(10, 10, 10, 10, 50),
         dataset = c("mcSCRB", "smartSeq3_fibroblasts", "smartSeq3_fibroblasts_alt", "smartSeq3_hek", "smartSeq3_siRNA_knockdown"))
```

```{r}
tmp <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices)  %>%
  mutate(knn_recovery = overlap / knn) %>%
  group_by(dataset, replicate, knn) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  tidylog::left_join(trans_families) 

sel_trans <- as.character(unique(tmp$transformation))


pl1 <- tmp %>%
 ggplot(aes(x = overlap, y = transformation, color = family)) +
    geom_vline(data = . %>% group_by(dataset) %>% summarize(mean = mean(overlap)), aes(xintercept = mean), size = 0.3, linetype = 2) +
    ggbeeswarm::geom_quasirandom(color = "grey", size = 0.3, alpha = 0.8, groupOnX = FALSE) +
    stat_summary(geom = "point", position = position_dodge2(width = 0.3), fun.data = mean_cl_boot) +
    scale_y_grouped_discrete(grouping = ~ trans_families_labels_mod[deframe(trans_families)[.x]], gap_size = 0.8, limits = rev,
                             labels = trans_labels[sel_trans], add_group_label = TRUE, guide = guide_grouped_axis()) +
    scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.2))) +
    scale_color_manual(values = trans_families_colors, labels = trans_families_labels, guide = "none") +
    facet_wrap(vars(dataset), ncol = 5, scales = "free_x", labeller = labeller(dataset = dataset_labels)) +
    theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt"),
                       axis.grouping.label.y = element_text(size = font_size_small, angle = 90)) +
    theme(axis.title.y = element_blank(),  plot.title.position = "plot", axis.text.x = element_text(size = font_size_tiny),
          strip.background = element_blank(), panel.spacing.x = unit(4, "mm")) +
    labs(title = "(D) Downsamping results considering only the top two transformations per approach")
pl1

```

```{r}
deepseq_overlap <- read_rds("../benchmark/output/benchmark_results/downsampling_deepseq_overlap.RDS")
```



```{r}
calc_pairwise_overlap <- function(dat){

  tmp <- dat %>%
    group_by(transformation, origin) %>%
    mutate(idx = rep(1:50)) %>%
    ungroup() %>%
    pivot_wider(c(transformation, origin), names_from = idx, values_from = neighbor, names_prefix = "neighbor_") %>%
    nest(cols = -transformation) %>%
    mutate(cols = map(cols, \(x) as.matrix(x[,-1])))
  
  names <- tmp$transformation
  similarity <- matrix(NA, nrow(tmp), nrow(tmp), dimnames = list(names, names))
  for(i in seq_len(nrow(tmp))){
    for(j in seq_len(nrow(tmp))){
      if(i < j){
        similarity[i,j] <- mean(sapply(seq_len(nrow(tmp$cols[[1]])), \(idx) length(intersect(tmp$cols[[i]][idx,], tmp$cols[[j]][idx,]))))
        similarity[j,i] <- similarity[i,j]
      }
    }
  }
  
  as_tibble(similarity, rownames = "A") %>%
    pivot_longer(-A, names_to = "B", values_to = "overlap")
}

pairwise_df <- map_df(deepseq_overlap, calc_pairwise_overlap, .id = "dataset")

```


```{r}
pairwise_pl <- pairwise_df %>%
  mutate(A = factor(A, levels(trans_families$transformation)),
         B = factor(B, levels(trans_families$transformation))) %>%
  ggplot(aes(x = A, y = B)) +
    geom_rect(xmin = 0, xmax = 27, ymin = 0, ymax = 27, fill = "#F2F2F2") +
    geom_tile(aes(fill = overlap)) +
    scale_fill_viridis_c() +
    gggroupedscale::scale_y_grouped_discrete(grouping = ~ trans_families_labels[deframe(trans_families)[.x]],
                                             gap_size = 0.4, limits = rev, labels = trans_labels, expand = expansion(add = 0)) +
    gggroupedscale::scale_x_grouped_discrete(grouping = ~ fct_rev(trans_families_labels[deframe(trans_families)[.x]]),
                                           gap_size = 0.4, limits= identity, labels = trans_labels, expand = expansion(add = 0)) +
    facet_wrap(vars(dataset), labeller = as_labeller(dataset_labels), nrow = 2) +
    guides(x = guide_axis(angle = 90)) +
    coord_fixed() +
    theme(axis.title = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(),
          strip.background = element_blank(), plot.title.position = "plot", 
          legend.position = c(0.7, 0.2), legend.direction = "horizontal") +
    labs(title = "(A) Pairwise $k$-NN overlap")

pairwise_pl
```


```{r}
overlap_df <- map_df(names(deepseq_overlap), \(dataset_name){
  tmp <- deepseq_overlap[[dataset_name]] %>%
    group_by(transformation, origin) %>%
    mutate(idx = rep(1:50)) %>%
    ungroup() %>%
    pivot_wider(c(transformation, origin), names_from = idx, values_from = neighbor, names_prefix = "neighbor_") %>%
    nest(cols = -transformation) %>%
    mutate(cols = map(cols, \(x) as.matrix(x[,-1])))
  
  full_knns <- tmp %>%
    filter(! transformation %in% c("raw_counts", "scaled_raw_counts")) 
  
  best_of_knns <- tmp %>%
    filter(transformation %in% sel_trans) 
  
  n_cells <- nrow(full_knns$cols[[1]])
  
  common_knns <- sapply(seq_len(n_cells), function(idx){
    merged_nn <- lapply(full_knns$cols, function(knn) knn[idx, ])
    length(purrr::reduce(merged_nn, intersect))
  })
  
  best_off_common_knns <- sapply(seq_len(n_cells), function(idx){
    merged_nn <- lapply(best_of_knns$cols, function(knn) knn[idx, ])
    length(purrr::reduce(merged_nn, intersect))
  })

  tibble(reliable_neighbors_per_cell = common_knns, reliable_neighbors_best_of_per_cell = best_off_common_knns,
         dataset = dataset_name)
})
```




```{r}
all_trans_hist <- overlap_df %>%
  pivot_longer(-dataset, values_to = "reliable_neighbors", names_to = "set") %>%
  count(dataset, set, reliable_neighbors) %>%
  filter(set == "reliable_neighbors_per_cell") %>%
  ggplot(aes(x = reliable_neighbors, y = n)) +
    geom_col(aes(fill = reliable_neighbors > 1), show.legend = FALSE) +
    scale_fill_manual(values = c("FALSE" = "lightgrey", "TRUE" = "black")) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    scale_x_continuous(limits = c(-0.5, 50), expand = expansion(add = 0)) +
    labs(x = "Reliable neighbors per cell", title = "(B) Histogram of reliable nearest neighbors per cell considering all transformations") +
    facet_wrap(vars(dataset), scales = "free", labeller = as_labeller(dataset_labels), nrow = 1) +
    theme(strip.background = element_blank(), plot.title.position = "plot") 

best_of_trans_hist <- overlap_df %>%
  pivot_longer(-dataset, values_to = "reliable_neighbors", names_to = "set") %>%
  count(dataset, set, reliable_neighbors) %>%
  filter(set == "reliable_neighbors_best_of_per_cell") %>%
  ggplot(aes(x = reliable_neighbors, y = n)) +
    geom_col(aes(fill = reliable_neighbors > 1), show.legend = FALSE) +
    scale_fill_manual(values = c("FALSE" = "lightgrey", "TRUE" = "black")) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
    scale_x_continuous(limits = c(-0.5, 50), expand = expansion(add = 0)) +
    labs(x = "Reliable neighbors per cell", title = "(C) Histogram of reliable nearest neighbors per cell considering only the top two transformations per approach") +
    facet_wrap(vars(dataset), scales = "free", labeller = as_labeller(dataset_labels), nrow = 1) +
    theme(strip.background = element_blank(), plot.title.position = "plot") 
```


```{r}
plot_assemble(
  list(plot = pairwise_pl,        x = 0, y =  0,   width = 180, height = 140),
  list(plot = all_trans_hist,     x = 0, y = 140,  width = 180, height = 30),
  list(plot = best_of_trans_hist, x = 0, y = 170,  width = 180, height = 30),
  list(plot = pl1,                x = 2, y = 200,  width = 150, height = 50),

  width = 180, height = 250, units = "mm", show_grid_lines = FALSE,
  filename = "../output/suppl-deep_seq_overlap.pdf", latex_support = TRUE
)
```


```{r}
best_of_results <- tmp %>%
  dplyr::select(benchmark, transformation, family, dataset, replicate, pca_dim, knn, overlap, knn_recovery) 

writexl::write_xlsx(list("Pairwise Overlap" = pairwise_df, "Reliable Nearest Neighbors" = overlap_df, "Best-of Results" = best_of_results), path = "../output/suppl-deep_seq_overlap_source_data.xlsx")
```


