---
title: "R Notebook"
---


```{r}
library(tidyverse)
library(gggroupedscale)
source("utils.R")
source("annotation_helper.R")
set.seed(1)
```

Load data

```{r}
res <- bind_rows(
  read_tsv("../benchmark/output/benchmark_results/simulation_results.tsv") %>% 
    transmute(benchmark = "simulation", overlap = mean_knn_overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset = simulator, replicate = seed, cputime_sec, elapsed_sec),
  read_tsv("../benchmark/output/benchmark_results/consistency_results.tsv") %>% 
    transmute(benchmark = "consistency", overlap = mean_overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset, replicate = seed, cputime_sec, elapsed_sec),
  read_tsv("../benchmark/output/benchmark_results/downsampling_results.tsv") %>% 
    transmute(benchmark = "downsampling", overlap = overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset, replicate = seed, cputime_sec = full_cputime_sec, elapsed_sec = full_elapsed_sec)
) %>%
  mutate(transformation = factor(transformation, levels = trans_families$transformation))
res
```

Define which parameters are shown for which dataset
```{r}
parameter_choices <- bind_rows(
  tibble(benchmark = "downsampling", knn = 50, pca_dim = c(10, 10, 10, 10, 50),
         dataset = c("mcSCRB", "smartSeq3_fibroblasts", "smartSeq3_fibroblasts_alt", "smartSeq3_hek", "smartSeq3_siRNA_knockdown")),
  tibble(benchmark = "simulation", knn = 50, pca_dim = c(5, 10, 10, 200, 50),
         dataset = c("dyngen", "linear_walk", "muscat", "random_walk", "scDesign2")),
  tibble(benchmark = "consistency", knn = 50, pca_dim = 50,
         dataset = unique(filter(res, benchmark == "consistency")$dataset)),
)
```

```{r}
comp_res <- res %>%
  filter(knn == 50) %>%
  mutate(alpha = ifelse(alpha == "0", "FALSE", alpha)) %>%
  tidylog::inner_join(dplyr::select(parameter_choices, -knn))  %>%
  mutate(knn_recovery = overlap / knn) %>%
  group_by(dataset, replicate) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  mutate(transformation = paste0(transformation, "-", alpha)) %>%
  transmute(transformation = transformation, benchmark, knn_recovery, knn) %>%
  drop_na() %>%
  pivot_wider(id_cols = c(knn, benchmark), names_from = transformation, values_from = knn_recovery, values_fill = list(NA_real_)) %>%
  mutate(benchmark = factor(benchmark, levels = rev(c("consistency", "simulation", "downsampling"))))


compare_conditions <- function(dat, a, b, bootstrap_replicates = 1000){
  if(!a %in% colnames(dat)) stop(a, " is not in the colnames")
  if(!b %in% colnames(dat)) stop(b, " is not in the colnames")
  dat %>%
    dplyr::transmute(benchmark, knn, A = .data[[a]], B = .data[[b]]) %>%
    rowwise() %>%
    mutate(bd = list(simpleboot::two.boot(B, A, mean, R = bootstrap_replicates))) %>% 
    ungroup() %>%
    mutate(mean_diff = map_dbl(bd, "t0"),
           mean_ci_low =  map_dbl(bd, ~ quantile(.x$t, probs = 0.025, na.rm = TRUE)),
           mean_ci_high = map_dbl(bd, ~ quantile(.x$t, probs = 0.975, na.rm = TRUE))) %>%
    dplyr::select(-c(A, B, bd))
}

make_comparison_plot <- function(cond_1, cond_2, label_cond_1 = cond_1, label_cond_2 = cond_2, add_dataset_label = FALSE, add_x_axis_label = FALSE, drop_na_level = FALSE){
  
  if(is.null(label_cond_1)){
    label_cond_1 <- trans_labels[str_split(cond_1, "-")[[1]][1]]
  }
  if(is.null(label_cond_2)){
    label_cond_2 <- trans_labels[str_split(cond_2, "-")[[1]][1]]
  }
  
  tmp <- compare_conditions(comp_res, cond_1, cond_2) %>%
    mutate(direction = case_when(
      is.na(mean_ci_low) | is.na(mean_ci_high) ~ "inconclusive",
      mean_ci_low <= 0 & mean_ci_high >= 0 ~  "inconclusive",
      mean_ci_low < 0 & mean_ci_high < 0 ~  "left",
      mean_ci_low > 0 & mean_ci_high > 0 ~  "right",
    )) %>%
    drop_na()
  
  arrow_pos <- if(drop_na_level){
    nrow(tmp) + 1.5
  }else{
    4.5
  }
  left_arrow_color <- trans_families_colors[deframe(trans_families)[str_split(cond_1, "-")[[1]][1]]]
  right_arrow_color <- trans_families_colors[deframe(trans_families)[str_split(cond_2, "-")[[1]][1]]]
  # extreme_val <- max(abs(c(min(tmp$mean_ci_low, na.rm = TRUE), max(tmp$mean_ci_high, na.rm = TRUE))))
  extreme_val <- 0.6
  
  ggplot(tmp, aes(x = mean_diff, y = benchmark)) +
      # geom_vline(xintercept = 0, size = 0.5, color = "grey", linetype = "dashed") +
      annotate("segment", x = 0, xend = 0, y = 0, yend = arrow_pos, color = "darkgrey", size = 0.5) +
      geom_pointrange(aes(xmin = mean_ci_low, xmax = mean_ci_high, group = as.factor(knn), color = direction), size = 0.5, fatten = 1.2) +
      annotate("segment", xend = extreme_val, x = extreme_val * 0.1, y = arrow_pos, yend = arrow_pos, arrow = arrow(length = unit(font_size_tiny / 2, "pt")), size = 0.8, color = right_arrow_color) +
      annotate("segment", xend = -extreme_val, x = -extreme_val * 0.1, y = arrow_pos, yend = arrow_pos, arrow = arrow(length = unit(font_size_tiny / 2, "pt")), size = 0.8, color = left_arrow_color) +
      annotate("text", x = -extreme_val * 0.55, y = arrow_pos + 0.3, label = label_cond_1, vjust = 0, size = font_size_small / .pt) +
      annotate("text", x = -extreme_val * 0.55, y = arrow_pos - 0.2, label =" better", vjust = 1, size = font_size_small / .pt) +
      annotate("text", x =  extreme_val * 0.55, y = arrow_pos + 0.3, label = label_cond_2, vjust = 0, size = font_size_small / .pt) +
      annotate("text", x =  extreme_val * 0.55, y = arrow_pos - 0.2, label = " better", vjust = 1, size = font_size_small / .pt) +
      (if(add_dataset_label) shadowtext::geom_shadowtext(aes(x = mean_ci_high, label = benchmark), hjust = -0.1, size = font_size_small / .pt, color = "#444444", bg.color = "white")
       else NULL) +
      scale_color_manual(values = c(left = "black", right = "black", inconclusive = "#444444"), guide = "none") +
      scale_x_continuous(breaks = c(-0.5, 0, 0.5), name = "Diff. Rel. $k$-NN Overlap") +
      scale_y_discrete(expand = expansion(add = c(0, 2.5)), drop = drop_na_level) +
      coord_cartesian(xlim = c(-extreme_val, extreme_val), clip = "off") +
      (if(add_x_axis_label){
        theme(plot.title = element_blank(),
              axis.title.y = element_blank(),
              axis.ticks.y = element_blank(),
              axis.text.y = element_blank(),
              axis.line.y = element_blank(),
              plot.margin = unit(c(0,4,2,4), "pt"))
        
      }else{
        theme(plot.title = element_blank(),
              axis.title = element_blank(),
              axis.ticks = element_blank(),
              axis.text = element_blank(),
              axis.line = element_blank(),
              plot.margin = unit(c(2,4,0,4), "pt"))
      })
}


alpha_comps <- list(
  list("acosh-FALSE", "acosh-TRUE", "$\\alpha=0$", "$\\alpha=\\textrm{est.}$"),
  list("pearson_clip-FALSE", "pearson_clip-TRUE", "$\\alpha=0$","$\\alpha=\\textrm{est.}$"),
  list("glmpca-FALSE", "glmpca-0.05", "$\\alpha=0$","$\\alpha=0.05$"),
  list("acosh-FALSE", "acosh-0.05", "$\\alpha=0$", "$\\alpha=0.05$"),
  list("pearson_clip-FALSE", "pearson_clip-0.05", "$\\alpha=0$", "$\\alpha=0.05$"),
  NULL
)

post_proc_comps <- list(
  list("logp1-FALSE", "logp1_size_normed-FALSE", NULL, NULL),
  list("logp1-FALSE", "logp1_hvg-FALSE", NULL, NULL),
  list("pearson_clip-TRUE", "pearson_clip_hvg-TRUE", NULL, NULL),
  list("pearson_clip-TRUE", "pearson_clip_zscore-TRUE", NULL, NULL)
)

cross_proc_comps <- list(
  list("logp1-FALSE", "sanity_map-FALSE", NULL, NULL),
  list("logp1-FALSE", "dino-FALSE", NULL, NULL),
  list("logp1-FALSE", "glmpca-FALSE", NULL, NULL),
  list("logp1-FALSE", "acosh-TRUE", NULL, NULL),
  list("logp1-FALSE", "pearson_clip-TRUE", NULL, NULL),
  
  list("pearson_clip-TRUE", "sanity_map-FALSE", NULL, NULL),
  list("pearson_clip-TRUE", "dino-FALSE", NULL, NULL),
  list("pearson_clip-TRUE", "glmpca-FALSE", NULL, NULL),
  list("pearson_clip-TRUE", "pearson_analytic-TRUE", NULL, NULL),
  list("pearson_clip-TRUE", "rand_quantile-TRUE", NULL, NULL)
)


alpha_pl_tmp <- pmap(list(.x=alpha_comps, .y=c(TRUE, rep(FALSE, 2),TRUE, rep(FALSE, 2)), .z=rep(c(FALSE, TRUE), each = 3)),
                          \(.x, .y, .z) if(is.null(.x)) NULL else make_comparison_plot(.x[[1]], .x[[2]], .x[[3]], .x[[4]], add_dataset_label = .y, drop_na_level = TRUE, add_x_axis_label = .z))
# alpha_theme_adapt <- theme(plot.margin = unit(c(4,4,4,4), "pt"), plot.subtitle = element_text(margin = unit(c(0,0,2,0), "pt")))
alpha_theme_adapt <- theme(plot.subtitle = element_text(margin = unit(c(0,0,2,0), "pt")))
alpha_pl_tmp[[1]] <-  alpha_pl_tmp[[1]] + labs(subtitle = trans_labels["acosh"])
alpha_pl_tmp[[2]] <-  alpha_pl_tmp[[2]] + labs(subtitle = trans_labels["pearson_clip"])
alpha_pl_tmp[[3]] <-  alpha_pl_tmp[[3]] + labs(subtitle = trans_labels["glmpca"])
alpha_comps_pl <- cowplot::plot_grid(plotlist = lapply(alpha_pl_tmp, function(x) x + alpha_theme_adapt),
                                     nrow = 2, rel_heights = c(1, 1.2))

post_proc_comps_pl <- cowplot::plot_grid(plotlist = pmap(list(.x=post_proc_comps, .y=c(TRUE, FALSE, TRUE, FALSE), .z=c(FALSE, FALSE, TRUE, TRUE)),
                                                         \(.x, .y, .z) make_comparison_plot(.x[[1]], .x[[2]], .x[[3]], .x[[4]], add_dataset_label = .y, add_x_axis_label = .z)),
                                         nrow = 2, rel_heights = c(1, 1.2))

cross_comps_pl <- cowplot::plot_grid(plotlist = pmap(list(.x=cross_proc_comps, .y=c(TRUE, rep(FALSE, 4),TRUE, rep(FALSE, 4)), .z = rep(c(FALSE, TRUE), each = 5)),
                                                     \(.x, .y, .z) make_comparison_plot(.x[[1]], .x[[2]], .x[[3]], .x[[4]], add_dataset_label = .y, add_x_axis_label = .z)),
                                     nrow = 2, rel_heights = c(1, 1.2))

```


```{r}
cross_comps_pl
post_proc_comps_pl
alpha_comps_pl
```



Recall per sequencing depth

```{r}
full_knn_overlaps <- bind_rows(
  bind_cols(read_tsv("../benchmark/output/benchmark_results/consistency_stratefication_results.tsv") %>%
              mutate(benchmark = "consistency") %>%
              dplyr::rename(replicate = seed),
         readRDS("../benchmark/output/benchmark_results/dataset_plot_data.RDS")$consistency[[7]] %>%
              dplyr::select(-name)),
  bind_cols(read_tsv("../benchmark/output/benchmark_results/simulation_stratefication_results.tsv") %>%
              mutate(benchmark = "simulation") %>%
              dplyr::select(-ground_truth_id) %>%
              dplyr::rename(dataset = simulator, replicate = seed),
            readRDS("../benchmark/output/benchmark_results/dataset_plot_data.RDS")$simulation[[5]] %>%
              dplyr::select(-c(simulator))),
  bind_cols(read_tsv("../benchmark/output/benchmark_results/downsampling_stratefication_results.tsv") %>%
              mutate(benchmark = "downsampling") %>%
              dplyr::rename(replicate = seed),
         readRDS("../benchmark/output/benchmark_results/dataset_plot_data.RDS")$downsampling[[5]] %>%
              dplyr::select(-name, col_sums = col_sums_reduced, tsne_log_counts_axis1 = tsne_log_counts_reduced_axis1, tsne_log_counts_axis2 = tsne_log_counts_reduced_axis2, -col_sums_full))
)
```


```{r}
loess_fits <- full_knn_overlaps %>%
  transmute(dataset, seq_depth = col_sums, 
            logp1 = `logp1-FALSE`, pearson_clip = `pearson_clip-TRUE`, sanity_map = `sanity_map-FALSE`, glmpca = `glmpca-FALSE`) %>%
  pivot_longer(c(logp1, pearson_clip, sanity_map, glmpca), names_to = "transformation", values_to = "overlap") %>%
  mutate(log_seq_depth = log(seq_depth)) %>%
  group_by(dataset) %>%
  filter(0.01 < percent_rank(seq_depth) & percent_rank(seq_depth) < 0.99) %>%
  group_by(dataset, transformation) %>%
  summarize(loess_fit = broom::augment(loess(overlap ~ log_seq_depth, span = 0.3)), .groups = "drop") %>% 
  unpack(loess_fit) %>%
  mutate(seq_depth = exp(log_seq_depth)) %>%
  left_join(trans_families) %>%
  left_join(enframe(dataset_labels, name = "dataset", value = "dataset_label")) %>%
  filter(family != "negative_control") %>%
  mutate(family = fct_drop(family)) 
```

```{r}
limits_df <- loess_fits %>%
  group_by(dataset) %>%
  summarize(max = max(.fitted))

knn_per_depth_pl <- full_knn_overlaps %>%
  transmute(dataset, seq_depth = col_sums, logp1 = `logp1-FALSE`, pearson_clip = `pearson_clip-0.05`, sanity_map = `sanity_map-FALSE`) %>%
  pivot_longer(c(logp1, pearson_clip, sanity_map), names_to = "transformation", values_to = "overlap") %>%
  left_join(limits_df) %>%
  filter(overlap < max * 2.5) %>%
  left_join(trans_families) %>%
  left_join(enframe(dataset_labels, name = "dataset", value = "dataset_label")) %>%
  ggplot(aes(x = seq_depth, y = overlap)) +
    annotation_logticks(sides = "b", short = unit(0.3, "mm"), mid = unit(0.3, "mm"), long = unit(0.5, "mm")) +
    ggrastr::rasterise(geom_point(alpha = 0.01, size = 0.01), dpi = 300) +
    # geom_line(data = filter(loess_fits, simulator == "linear_walk"), aes(y = .fitted, color = family), size = 0.9) +
    geom_line(data = loess_fits, aes(y = .fitted, color = family), size = 0.9) +
    scale_x_log10() +
    # scale_y_continuous(breaks = c(0, 5, 10, 20, 30, 40, 50)) +
    # coord_cartesian(ylim = c(0, 50), clip = "off") +
    scale_color_manual(values = trans_families_colors[-5], labels = as.character(trans_families_labels_long[-5]), name = "") +
    facet_wrap(vars(dataset_label), scales = "free") +
    labs(y = "$k$-NN Overlap", x = "UMIs / cell",
         title = "(D) More UMIs/cell, better $k$-NN overlap") +
    theme(plot.title.position = "plot", plot.margin = unit(c(4,4,1,1), "pt"),
          plot.title = element_text(margin = unit(c(0, 0, 8, 0), "pt")),
          strip.background = element_blank(), strip.text = element_text(size = font_size_small),
          # legend.position = "bottom", legend.background = element_rect(fill = "#FFFFFFBB")
          )
    
knn_per_depth_pl
```



```{r fig.height=3.71, fig.width=6.69, dev="ragg_png"}
plot_assemble(
  annotate_text("(A) $\\log(y/s+1)$ performs on par or better than alternative transformations", fontsize = font_size, x = 0, y = 2, vjust = 1, fontface = "bold"),
  list(plot = cross_comps_pl, x = 0, y = 6, width = 180, height = 45),
  annotate_text("(B) Post-processing does not consistently\n\\qquad improve results", fontsize = font_size, x = 0, y = 52, vjust = 1, fontface = "bold"),
  list(plot = post_proc_comps_pl, x = 0, y = 58, width = 72, height = 45),
  annotate_text("(C) Non-zero overdispersion improves results for delta method\n\\qquad and Pearson transformation", fontsize = font_size, x = 74, y = 52, vjust = 1, fontface = "bold"),
  list(plot = alpha_comps_pl, x = 74, y = 58, width = 106, height = 45),
  list(plot = knn_per_depth_pl + guides(color = "none"), x = 0, y = 103, width = 180, height = 30),
  list(plot = cowplot::get_legend(knn_per_depth_pl), x = 153, y = 77, width = 30, height = 20),
  width = 180, height = 134, units = "mm", show_grid_lines = FALSE,
  filename = "../output/main_contrasts_fig.pdf", latex_support = TRUE
)
```

```{r}
contrast_data <- res %>%
  filter(knn == 50) %>%
  mutate(alpha = ifelse(alpha == "0", "FALSE", alpha)) %>%
  tidylog::inner_join(dplyr::select(parameter_choices, -knn))  %>%
  mutate(knn_recovery = overlap / knn) %>%
  group_by(dataset, replicate) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  dplyr::select(benchmark, transformation, dataset, replicate, pca_dim, alpha, knn, knn_recovery) 

depth_vs_overlap <- full_knn_overlaps %>%
  transmute(dataset, seq_depth = col_sums, logp1 = `logp1-FALSE`, pearson_clip = `pearson_clip-0.05`, sanity_map = `sanity_map-FALSE`) %>%
  pivot_longer(c(logp1, pearson_clip, sanity_map), names_to = "transformation", values_to = "overlap") %>%
  left_join(trans_families) %>%
  left_join(enframe(dataset_labels_plain, name = "dataset", value = "dataset_label")) %>%
  dplyr::select(dataset, dataset_label, seq_depth, transformation, family, overlap)

writexl::write_xlsx(list("Contrast Data" = contrast_data, "Seq. Depth vs kNN Trend" = depth_vs_overlap), path = "../output/main_contrasts_fig_source_data.xlsx")
```


# Session Info

```{r}
sessionInfo()
```