---
title: "R Notebook"
---



```{r}
library(tidyverse)
library(tidylog)
library(SingleCellExperiment)
source("utils.R")
source("annotation_helper.R")

source("../benchmark/src/transformations/transformation_helper.R")
.SANITY_FOLDER <- "/Users/ahlmanne/prog/experiments/Sanity"
set.seed(1)
```



```{r}
if(! file.exists("../extra_data//svensson_2017_1.h5ad")){
  download.file("https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/", "../extra_data/svensson_2017_1.h5ad")
}
se <- zellkonverter::readH5AD("../extra_data/svensson_2017_1.h5ad", reader = "R")
se <- se[,sample.int(ncol(se), 400)]

size_factors <- colSums2(assay(se, "X"))
size_factors <- size_factors / mean(size_factors)
summary(size_factors)

Y <- as.matrix(assay(se, "X"))
Y <- Y[rowSums2(Y) > 0, ]
rownames(Y) <- paste0("Gene_", seq_len(nrow(Y)))
colnames(Y) <- paste0("Cell_", seq_len(ncol(Y)))
# overdisp <- glmGamPoi::glm_gp(se, overdispersion = "global", 
#                               overdispersion_shrinkage = FALSE, on_disk = FALSE)$overdispersions[1]
overdisp <- TRUE
```


```{r}
transformed_dat <- list()
for(trans in names(all_transformations)){
  print(paste0("Applying trans: ", trans))
  transformed_dat[[trans]] <- all_transformations[[trans]](Y, sf = size_factors, alpha = overdisp)
}
# Keeping it at TRUE means that glmpca does not converge
attr(transformed_dat$glmpca, "alpha") <- FALSE  
```



```{r}
saveRDS(list(transformed_dat = transformed_dat), "../extra_data/svensson_2017_1_transformed.Rds")
# tmp <- readRDS( "../extra_data/svensson_2017_1_transformed.Rds")
# transformed_dat <- tmp$transformed_dat
```


```{r}
tmp <- enframe(transformed_dat, name = "transformation", value = "transformed_data") %>%
  mutate(pca = map2(transformation, transformed_data, function(name, dat){
   if(name == "sanity_dists") cmdscale(as.matrix(dat), k = 10)
   else if(name == "glmpca"){
    pca_res <- glmpca::glmpca(Y = dat, L = 10, fam = if(isFALSE(attr(dat, "alpha"))) "poi" else "nb",
                              sz = attr(dat, "size_factor"), nb_theta = 1/attr(dat, "alpha"))
    as.matrix(pca_res$factors)
   }else if(name == "newwave"){
    se <- SummarizedExperiment::SummarizedExperiment(assay = list(counts = dat))
    pca_res <- NewWave::newWave(Y = se, K = 10, n_gene_disp = 100, children = 4)
    SingleCellExperiment::reducedDim(pca_res, "newWave")
   }else irlba::prcomp_irlba(t(dat), n = 10)$x 
  })) %>%
  transmute(transformation, pca, cell_name = list(paste0("cell_", seq_len(ncol(Y))))) %>%
  unnest(c(pca, cell_name)) %>%
  left_join(tibble(cell_name = paste0("cell_", seq_len(ncol(Y))), size_factor = size_factors)) 
```


```{r}
can_cor_res <- tmp %>%
  mutate(transformation2 = factor(transformation, levels = as.character(trans_families$transformation)),
         transformation_labelled = factor(trans_labels[as.character(transformation2)], levels = trans_labels[as.character(trans_families$transformation)])) %>% 
  group_by(transformation, transformation_labelled) %>%
  summarize(canonical_correlation = cancor(pca, size_factor)$cor, .groups = "drop") %>%
  left_join(trans_families) %>%
  mutate(transformation = factor(transformation, levels = trans_families$transformation))

cor_pl <- can_cor_res %>%
  ggplot(aes(x = canonical_correlation, y = transformation, fill = family)) +
    geom_col() +
    geom_vline(xintercept = 1, size = 0.3) +
    gggroupedscale::scale_y_grouped_discrete(grouping = ~ trans_families_labels[deframe(trans_families)[.x]], gap_size = 1.3, limits = rev,
                         labels = trans_labels, add_group_label = TRUE) +
    scale_x_continuous(expand = expansion(add = c(0, 0.1))) +
    scale_fill_manual(values = trans_families_colors, labels = trans_families_labels, guide = "none") +
    labs(x = "Canonical Correlation",
         title = "Influence of size factor on PCA embedding",
         subtitle = "Smaller values are better") +
    gggroupedscale::theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt"), axis.grouping.label.y = element_text(size = font_size_small, angle = 90)) +
    theme(axis.title.y = element_blank(),  plot.title.position = "plot")

res <- tmp %>%
  mutate(transformation2 = factor(transformation, levels = as.character(trans_families$transformation)),
         transformation_labelled = factor(trans_labels[as.character(transformation2)], levels = trans_labels[as.character(trans_families$transformation)])) %>% 
  left_join(trans_families) %>%
  mutate(family = factor(family, levels = unique(trans_families$family))) %>%
  group_by(transformation) %>%
  mutate(pca = pca * 10 / quantile(abs(pca), 0.99)) %>%
  group_by(family) %>%
  group_map(function(dat, key){
    cat <- key[[1]][1]
    ggplot(dat, aes(x = pca[,1], y = pca[,2])) +
      geom_hline(yintercept = -15, size = 0.4) + geom_vline(xintercept = -15, size = 0.4) +
      ggrastr::rasterize(geom_point(aes(color = size_factor), size = 0.7), dpi = 300, scale = 2/3) +
      shadowtext::geom_shadowtext(data = filter(can_cor_res, family == cat), aes(label = paste0("$\\rho = ", signif(canonical_correlation, digits = 2), "$")),
                                  x = 0, y = -Inf,  hjust = 0.5, vjust = -0.5, size = font_size_small / .pt,
                                  color = "black", bg.colour = "white", inherit.aes = FALSE) +
      ggh4x::facet_wrap2(vars(transformation_labelled), ncol = if(cat %in% c("count_model", "negative_control")) 2 else 4, 
                                                                  strip = ggh4x::strip_vanilla(clip = "off"), trim_blank = FALSE) +
      coord_fixed(xlim = c(-15, 15), ylim = c(-15, 15)) +
      scale_x_continuous(expand = expansion(0)) +
      scale_y_continuous(expand = expansion(0)) +
      scale_color_viridis_c(limits = c(0.333, 3), breaks = c(0.4, 1, 2.5), oob = scales::squish, trans = "log2",
                            guide = if(cat == "count_model") guide_colorbar() else "none") +
      labs(x = "PC 1", y = "PC 2", color = "Size Factor",
           title = trans_families_labels_long[as.character(cat)]) +
      theme(legend.key.size = unit(font_size_small, "pt"),
            legend.title = element_text(size = font_size_small),
            axis.ticks = element_blank(), axis.text = element_blank(), axis.line = element_blank(),
            strip.text = element_text(size = font_size_tiny),
            strip.background = element_blank()) 
  })

legend <- cowplot::get_legend(res[[4]])
res[[4]] <- cowplot::plot_grid(res[[4]] + guides(color = "none"),
                               res[[5]] + theme(axis.title.y = element_blank()), nrow = 1, align = "v", axis = "l")
res[[5]] <- NULL

comb_pl <- cowplot::plot_grid(plotlist = res, nrow = 4, rel_heights = c(2, 2, 1.16, 1.16))

plot_assemble(annotate_text("(A)", x = 2,  y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              list(plot = comb_pl, x = 0,  y = 4,    width = 90, height = 180),
              annotate_text("(B)", x = 95,  y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              list(plot = cor_pl,  x = 95, y = 4,    width = 60, height = 80),
              list(plot = cowplot::plot_grid(cowplot::ggdraw() + cowplot::draw_grob(legend)), x = 90, y = 65, width = 180, height = 70),
              width = 155, height = 184, units = "mm", show_grid_lines = FALSE,
              filename = "../output/suppl-seq_depth_homogeneous_data_pattern.pdf", latex_support = TRUE)
```

```{r}
pca_plot_data <- tmp %>%
  mutate(pca = as_tibble(pca, .name_repair = \(.) paste0("PC_", 1:10))) %>%
  tidyr::unpack(pca)

can_cor_res_for_saving <- can_cor_res %>%
  dplyr::select(transformation, family, canonical_correlation)
  
writexl::write_xlsx(list("PCA Data" = pca_plot_data, "Canonical Correlation" = can_cor_res_for_saving), path = "../output/suppl-seq_depth_homogeneous_data_pattern_source_data.xlsx")
```

# Session Info

```{r}
sessionInfo()
```


 