---
title: "R Notebook"
---


```{r}
library(tidyverse)
library(gggroupedscale)
source("utils.R")
source("annotation_helper.R")
```

Load data

```{r}
res <- bind_rows(
  read_tsv("../benchmark/output/benchmark_results/simulation_results.tsv") %>% 
    transmute(benchmark = "simulation", overlap = mean_knn_overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset = simulator, replicate = seed, cputime_sec, elapsed_sec),
  read_tsv("../benchmark/output/benchmark_results/consistency_results.tsv") %>% 
    transmute(benchmark = "consistency", overlap = mean_overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset, replicate = seed, cputime_sec, elapsed_sec),
  read_tsv("../benchmark/output/benchmark_results/downsampling_results.tsv") %>% 
    transmute(benchmark = "downsampling", overlap = overlap, knn, pca_dim, alpha = as.character(alpha), transformation, dataset, replicate = seed, cputime_sec = full_cputime_sec, elapsed_sec = full_elapsed_sec)
) %>%
  mutate(transformation = factor(transformation, levels = trans_families$transformation))
res
```

Define which parameters are shown for which dataset
```{r}
parameter_choices <- bind_rows(
  tibble(benchmark = "downsampling", knn = 50, pca_dim = c(10, 10, 10, 10, 50),
         dataset = c("mcSCRB", "smartSeq3_fibroblasts", "smartSeq3_fibroblasts_alt", "smartSeq3_hek", "smartSeq3_siRNA_knockdown")),
  tibble(benchmark = "simulation", knn = 50, pca_dim = c(5, 10, 10, 200, 50),
         dataset = c("dyngen", "linear_walk", "muscat", "random_walk", "scDesign2")),
  tibble(benchmark = "consistency", knn = 50, pca_dim = 50,
         dataset = unique(filter(res, benchmark == "consistency")$dataset)),
)
```

```{r}
print(paste0(sum(res$cputime_sec) / (60 * 60 * 24 * 356), " years total compute time"))
```


# Headline plot



Make the main benchmark overview panels
```{r}
res_main <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices)  %>%
  mutate(knn_recovery = overlap / knn) %>%
  group_by(dataset, replicate, knn) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  tidylog::left_join(trans_families)

make_main_plot_panel <- function(data, add_group_label = FALSE){
  ggplot(data, aes(x= knn_recovery, y = transformation, color = family)) +
    geom_vline(xintercept = 1, size = 0.3, linetype = 2) +
    ggbeeswarm::geom_quasirandom(color = "grey", size = 0.3, alpha = 0.7, groupOnX = FALSE) +
    stat_summary(geom = "point", position = position_dodge2(width = 0.3), fun.data = mean_cl_boot, fatten = 1.8) +
    scale_y_grouped_discrete(grouping = ~ trans_families_labels[deframe(trans_families)[.x]], gap_size = 1.7, limits = rev,
                             labels = trans_labels, add_group_label = add_group_label, guide = if(add_group_label) guide_grouped_axis() else guide_axis()) +
    scale_x_continuous(breaks = c(0.5, 1, 1.5)) +
    coord_cartesian(xlim = c(0.2, 1.8)) +
    scale_color_manual(values = trans_families_colors, labels = trans_families_labels, guide = "none") +
    theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt"), axis.grouping.label.y = element_text(size = font_size_small, angle = 90)) +
    theme(axis.title.y = element_blank(),  plot.title.position = "plot")
}

consistency_pl <- res_main %>%
  filter(benchmark == "consistency") %>%
  make_main_plot_panel(add_group_label = TRUE) +
  labs(x = "Relative $k$-NN Overlap", 
       subtitle = "10X gene subset A vs. gene subset B") +
  NULL

simulation_pl <- res_main %>%
  filter(benchmark == "simulation") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       subtitle = "Ground truth vs. simulated counts") +
  NULL


downsampling_pl <- res_main %>%
  filter(benchmark == "downsampling") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       subtitle = "Original vs. downsampled Smart-seq3 data") +
  NULL

consistency_pl
simulation_pl
downsampling_pl
```




Make the same panels but with $k=10$ and $k=100$
```{r}
res_alt_knn <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(dplyr::select(parameter_choices, -knn))  %>%
  filter(knn != parameter_choices$knn[1]) %>%
  mutate(knn_recovery = overlap / knn) %>%
  group_by(dataset, replicate, knn) %>%
  mutate(knn_recovery = knn_recovery / mean(knn_recovery)) %>%
  tidylog::left_join(trans_families)

suppl_con_k10 <- res_alt_knn %>%
  filter(knn == 10) %>%
  filter(benchmark == "consistency") %>%
  make_main_plot_panel(add_group_label = TRUE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(A) Consistency: $k = 10$") +
  NULL

suppl_con_k100 <- res_alt_knn %>%
  filter(knn == 100) %>%
  filter(benchmark == "consistency") %>%
  make_main_plot_panel(add_group_label = TRUE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(B) Consistency: $k = 100$") +
  NULL

suppl_sim_k10 <- res_alt_knn %>%
  filter(knn == 10) %>%
  filter(benchmark == "simulation") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(C) Simulation: $k = 10$") +
  NULL

suppl_sim_k100 <- res_alt_knn %>%
  filter(knn == 100) %>%
  filter(benchmark == "simulation") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(D) Simulation: $k = 100$") +
  NULL


suppl_dow_k10 <- res_alt_knn %>%
  filter(knn == 10) %>%
  filter(benchmark == "downsampling") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(E) Downsampling: $k = 10$") +
  NULL

suppl_dow_k100 <- res_alt_knn %>%
  filter(knn == 100) %>%
  filter(benchmark == "downsampling") %>%
  make_main_plot_panel(add_group_label = FALSE) +
  labs(x = "Relative $k$-NN Overlap", 
       title = "(F) Downsampling: $k = 100$") +
  NULL

plot_assemble(list(plot = suppl_con_k10,    x = 0,  y = 0,    width = 60, height = 75),
              list(plot = suppl_con_k100,   x = 0, y = 75,    width = 60, height = 75),
              list(plot = suppl_sim_k10,    x = 60,  y = 0,   width = 60, height = 75),
              list(plot = suppl_sim_k100,   x = 60, y = 75,   width = 60, height = 75),
              list(plot = suppl_dow_k10,    x = 120,  y = 0,  width = 60, height = 75),
              list(plot = suppl_dow_k100,   x = 120, y = 75,  width = 60, height = 75),
              width = 180, height = 150, units = "mm", show_grid_lines = FALSE,
              filename = "../output/suppl_alt_k_benchmark.pdf", latex_support = TRUE)

```


```{r}
res_full_bench <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices)  %>%
  tidylog::left_join(trans_families)

dataset_labels_mod <- enframe(dataset_labels, name = "dataset", value = "label") %>%
  left_join(parameter_choices, by = "dataset") %>%
  mutate(label = paste0(label, " (\\#PCs=", pca_dim, ")")) %>%
  dplyr::select(dataset, label) %>%
  deframe()

make_main_suppl_plot_panels <- function(data, add_group_label = FALSE){
  ggplot(data, aes(x = overlap, y = transformation, color = family)) +
    geom_vline(data = . %>% group_by(dataset) %>% summarize(mean = mean(overlap)), aes(xintercept = mean), size = 0.3, linetype = 2) +
    ggbeeswarm::geom_quasirandom(color = "grey", size = 0.3, alpha = 0.8, groupOnX = FALSE) +
    stat_summary(geom = "point", position = position_dodge2(width = 0.3), fun.data = mean_cl_boot, fatten = 1.8) +
    scale_y_grouped_discrete(grouping = ~ trans_families_labels[deframe(trans_families)[.x]], gap_size = 1.5, limits = rev,
                             labels = trans_labels, add_group_label = add_group_label, guide = if(add_group_label) guide_grouped_axis() else guide_axis()) +
    scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.2))) +
    scale_color_manual(values = trans_families_colors, labels = trans_families_labels, guide = "none") +
    facet_wrap(vars(dataset), ncol = 5, scales = "free_x", labeller = labeller(dataset = dataset_labels_mod)) +
    theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt"), axis.grouping.label.y = element_text(size = font_size_small, angle = 90)) +
    theme(axis.title.y = element_blank(),  plot.title.position = "plot", axis.text.x = element_text(size = font_size_tiny), strip.background = element_blank()) 
}

con_suppl_pl <- res_full_bench %>%
  filter(benchmark == "consistency") %>%
  make_main_suppl_plot_panels(add_group_label = TRUE) +
  labs(title = "(A) Consistency: 10X gene subset A vs. gene subset B", x = "$k$-NN Overlap")

sim_suppl_pl <- res_full_bench %>%
  filter(benchmark == "simulation") %>%
  make_main_suppl_plot_panels(add_group_label = TRUE) +
  labs(title = "(B) Simulation: Ground truth vs. simulated counts", x = "$k$-NN Overlap")

dow_suppl_pl <- res_full_bench %>%
  filter(benchmark == "downsampling") %>%
  make_main_suppl_plot_panels(add_group_label = TRUE) +
  labs(title = "(C) Downsampling: Original vs. downsampled Smart-seq3 data", x = "$k$-NN Overlap")

plot_assemble(
  list(plot = con_suppl_pl, x = 0, y = 0, width = 180, height = 120),
  list(plot = sim_suppl_pl, x = 0, y = 120, width = 180, height = 65),
  list(plot = dow_suppl_pl, x = 0, y = 185, width = 180, height = 65),
  width = 180, height = 250, units = "mm", show_grid_lines = FALSE,
  filename = "../output/suppl-raw_benchmark_results.pdf", latex_support = TRUE
)

```


# Number of PCA dimensions are important

```{r}
pca_dat <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  filter(knn == 50) %>%
  mutate(knn_recovery = overlap) %>%
  tidylog::group_by(benchmark, dataset, pca_dim, transformation) %>%
  tidylog::summarize(knn_recovery = mean(knn_recovery), .groups = "drop") %>%
  tidylog::left_join(trans_families) %>%
  mutate(transformation = fct_reorder(transformation, runif(n()))) %>%
  mutate(is_dim_indep = transformation == "sanity_dists")


make_pca_plot_panel <- function(data, long_x_scale, breaks = c(0)){
  ggplot(data, aes(x = pca_dim, y = knn_recovery)) +
    geom_line(aes(group = transformation, color = family, linetype = is_dim_indep), size = 0.4, show.legend = FALSE) +
    (if(long_x_scale) scale_x_log10(breaks = c(10, 100, 1000, 1e5), labels = expression(10^1, 10^2, 10^3, "all")) 
     else scale_x_log10(breaks = c(5, 10, 50, 100))) +
    scale_color_manual(values = trans_families_colors) +
    scale_y_continuous(limits = c(0, NA), breaks = breaks) +
    scale_linetype_manual(values = c(`TRUE` = "dashed", `FALSE`  = "solid")) +
    labs(y = "$k$-NN\nOverlap", x = "\\#PCA-dimensions")
}

pca_pl_random_walk <- pca_dat %>%
  filter(dataset == "random_walk") %>%
  make_pca_plot_panel(long_x_scale = TRUE, breaks = c(0, 20, 40)) +
  labs(title = "Random Walk (Simulation)") +
  theme(plot.title = element_text(face = "plain", size = font_size_small, hjust = 0.5, margin = margin(), lineheight = 0.8)) 

pca_pl_scDesign2 <- pca_dat %>%
  filter(dataset == "scDesign2") %>%
  make_pca_plot_panel(long_x_scale = TRUE, breaks = c(0, 5, 10)) +
  labs(title = "scDesign2 (Simulation)") +
  theme(plot.title = element_text(face = "plain", size = font_size_small, hjust = 0.5, margin = margin(), lineheight = 0.8)) 


pca_pl_siRNA_kd <- pca_dat %>%
  filter(dataset == "smartSeq3_siRNA_knockdown") %>%
  make_pca_plot_panel(long_x_scale = FALSE, breaks = c(0, 5)) +
  labs(title = "siRNA KD (Downsampling)") +
   theme(plot.title = element_text(face = "plain", size = font_size_small, hjust = 0.5, margin = margin(), lineheight = 0.8)) 


pca_pl_10X <- pca_dat %>%
  filter(dataset == "GSE179714") %>%
  make_pca_plot_panel(long_x_scale = FALSE, breaks = c(0, 25)) +
  labs(title = "GSE179714 (Consistency)") +
  theme(plot.title = element_text(face = "plain", size = font_size_small, hjust = 0.5, margin = margin(), lineheight = 0.8)) 

```


```{r}
plot_assemble(annotate_text("(A)", x = 2, y =1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_text("Consistency", x = 21, y =1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_text("(B)", x = 62, y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_text("Simulation", x = 82, y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_text("(C)", x = 122, y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_text("Downsampling", x = 137, y = 1, vjust = 1, fontsize = font_size, fontface = "bold"),
              annotate_graphic("../illustrations/benchmark_overviewArtboard 1.pdf", x = 32,  y = 104, units = "mm"),
              annotate_graphic("../illustrations/benchmark_overviewArtboard 3.pdf", x = 92,  y = 104, units = "mm"),
              annotate_graphic("../illustrations/benchmark_overviewArtboard 2.pdf", x = 152, y = 104, units = "mm"),
              list(plot = consistency_pl,     x = 0,  y = 18,    width = 60, height = 70),
              list(plot = simulation_pl,      x = 60, y = 18,    width = 60, height = 70),
              list(plot = downsampling_pl,    x = 120,  y = 18,   width = 60, height = 70),
              annotate_text("(D) $k$-NN overlap depends on \\#PCA-dimensions", x = 2, y = 92, fontsize = font_size, fontface = "bold"),
              list(plot = pca_pl_random_walk, x = 0,   y = 92,  width = 44, height = 23),
              list(plot = pca_pl_scDesign2,   x = 45,  y = 92,  width = 44, height = 23),
              list(plot = pca_pl_siRNA_kd,    x = 90,  y = 92,  width = 44, height = 23),
              list(plot = pca_pl_10X,         x = 135, y = 92,  width = 44, height = 23),
              width = 180, height = 115, units = "mm", show_grid_lines = FALSE,
              filename = "../output/main_benchmark_fig.pdf", latex_support = TRUE)
```


# Duration plots

```{r}
sel_dataset <- "GSE179831" 
rel_scaling_factor_lin <- median(filter(res, transformation == "logp1", dataset == sel_dataset, pca_dim == 10, knn == 50)$cputime_sec)

perf_plot <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  filter(dataset == sel_dataset, pca_dim == 10, knn == 50) %>%
  tidylog::left_join(trans_families) %>%
  ggplot(aes(x = transformation, y = cputime_sec)) +
    geom_hline(yintercept = rel_scaling_factor_lin, linetype = 2, color = "darkgrey", size = 0.5) +
    geom_hline(yintercept = rel_scaling_factor_lin * c(10, 100, 1000, 10000), linetype = 2, color = "grey", size = 0.3) +
    stat_summary(geom = "point", aes(color = family), position = position_dodge2(width = 0.3), fun.data = mean_sdl, fatten = 1.8) +
    geom_text(data = data.frame(y = 10^seq(0, 4), y_lab = c("1", "10", "100", "1\\,000", "10\\,000")), aes(y = rel_scaling_factor_lin * y, label = paste0("$", y_lab, "\\times$")),
              x = 27, hjust = 1, vjust = -0.3, size = font_size_small / .pt) +
    scale_x_grouped_discrete(grouping = ~ fct_rev(trans_families_labels[deframe(trans_families)[.x]]), gap_size = 1.5, 
                             labels = trans_labels, add_group_label = TRUE, guide =  guide_grouped_axis(angle = 90)) +
    scale_y_log10(breaks = c(0.001, 1, 60, 60 * 60, 24 * 60 * 60, 7 * 24 * 60 * 60), expand = expansion(mult = c(0.1, 0.01)),
        labels = c("1 ms", "1 sec", "1 min", "1 hour", "1 day", "1 week"), name = "",
        sec.axis = sec_axis(trans = ~ .x / rel_scaling_factor_lin, breaks = c(1, 10, 100, 1000, 10000))) +
    coord_cartesian(clip = "off") +
    scale_color_manual(values = trans_families_colors, guide = "none") +
    theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt"), axis.grouping.label.x = element_text(size = font_size_small)) +
    theme(axis.title.x = element_blank(), axis.text.y.right = element_blank(), axis.ticks.y.right = element_blank(), plot.title.position = "plot") +
    labs(title = "(A) Computational expense for transform and $k$-NN calculation", y = "")
  

perf_plot

```



```{r}
dataset_summaries <- read_tsv("../benchmark/output/benchmark_results/dataset_summaries.tsv") %>%
  dplyr::rename(dataset = name)
```

```{r}
res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  filter(pca_dim == 10) %>%
  left_join(trans_families) %>%
  left_join(dataset_summaries %>% dplyr::select(-c(row_means, row_vars))) %>%
  mutate(highlight = case_when(
    transformation == "sanity_dists" ~ "sanity_dist",
    transformation == "sanity_map" ~ "sanity_map",
    transformation == "logp1_hvg" ~ "logp1_hvg",
    transformation == "pearson_analytic" ~ "pearson_analytic",
    transformation == "glmpca" ~ "glmpca",
    transformation == "dino" ~ "dino",
    TRUE ~ "other"
  )) %>%
  ggplot(aes(x = n_cells, y = cputime_sec)) +
    geom_point() +
    # geom_line(aes(color = highlight, group = transformation)) +
    geom_smooth(aes(color = highlight, group = transformation), method = "lm") +
    scale_x_log10() +
    scale_y_log10()
```

```{r}
# duration_dat <- res %>%
#   # filter(alpha %in% c("TRUE", "FALSE")) %>%
#   # filter(pca_dim == 10, knn == 50) %>%
#   filter(knn == 50) %>%
#   left_join(trans_families) %>%
#   left_join(dataset_summaries %>% dplyr::select(-c(row_means, row_vars))) %>%
#   mutate(highlight = case_when(
#     transformation == "sanity_dists" ~ "sanity_dist",
#     transformation == "sanity_map" ~ "sanity_map",
#     transformation == "logp1_hvg" ~ "logp1_hvg",
#     transformation == "pearson_analytic" ~ "pearson_analytic",
#     transformation == "glmpca" ~ "glmpca",
#     transformation == "dino" ~ "dino",
#     TRUE ~ "other"
#   )) %>%
#   filter(highlight != "other") %>%
#   filter(!is.na(cputime_sec)) %>%
#   mutate(pca_dim = pmin(pca_dim, n_cells, n_genes))
# 
# fit <- lm(cputime_sec ~ transformation * (n_genes + I(n_genes^2) + poly(n_cells, 4) + poly(pca_dim, 4)) -1, data = duration_dat)
# # fit <- lm(log(cputime_sec) ~ transformation * (poly(n_genes, 3) + poly(n_cells, 4) + poly(pca_dim, 4)) -1, data = duration_dat)
# summary(fit)
# 
# predict_df <- duration_dat %>%
#   dplyr::select(transformation, n_genes, n_cells, proportion_zeros) %>%
#   mutate(cputime_sec = (predict(fit, newdata = duration_dat)))
# 
# resid_df <- bind_cols(duration_dat, error = residuals(fit, newdata = duration_dat))
# resid_df %>%
#   ggplot(aes(x = n_cells, y = error, color = as.factor(pca_dim))) +
#     geom_hline(yintercept = 0) +
#     geom_point() +
#     facet_wrap(vars(transformation), scales = "free")
# 
# duration_dat %>%
#   ggplot(aes(x = n_cells, y = cputime_sec, color = transformation)) +
#     geom_point() +
#     geom_line(data = predict_df) +
#     # coord_trans(y = "log10", ylim = c(1, 1e7)) 
#     facet_wrap(vars(transformation), scales = "free_y")
# 
# cross_df(list(n_genes = 10000, proportion_zeros = 0.8, pca_dim = 40, n_cells = seq(1000, 3e4, length.out = 101), dataset = "scDesign2",
#              transformation = c("sanity_dists", "sanity_map", "logp1_hvg", "pearson_analytic", "glmpca", "dino"))) %>%
#   mutate(cputime_sec = (predict(fit, newdata = .))) %>%
#   ggplot(aes(x = n_cells, y = cputime_sec, color = transformation)) +
#     geom_line() +
#     facet_wrap(vars(transformation), scales = "free_y")

```


```{r}
time_minor_ticks <- tibble(ticks = c(seq(0, 60, by = 10), # seconds
                                     seq(0, 60 * 60, by = 10 * 60), # 10 minutes
                                     seq(0, 24 * 60 * 60, by = 6 * 60 * 60),  # 6 hours
                                     seq(0, 7 * 24 * 60 * 60, by = 24 * 60 * 60), # 1 day
                                     seq(0, 8* 7 * 24 * 60 * 60, by = 5 * 24 * 60 * 60))) # 4 weeks
time_major_ticks <- tibble(ticks = c(1, 60, 60 * 60, 24 * 60 * 60, 7 * 24 * 60 * 60))

res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  filter(pca_dim == 10) %>%
  left_join(trans_families) %>%
  left_join(dataset_summaries %>% dplyr::select(-c(row_means, row_vars))) %>%
  mutate(highlight = case_when(
    transformation == "sanity_dists" ~ "sanity_dist",
    transformation == "sanity_map" ~ "sanity_map",
    transformation == "logp1_hvg" ~ "logp1_hvg",
    transformation == "pearson_analytic" ~ "pearson_analytic",
    transformation == "dino" ~ "dino",
    TRUE ~ "other"
  )) %>%
  ggplot(aes(x = n_cells, y = cputime_sec)) +
    ggrastr::rasterise(ggbeeswarm::geom_quasirandom(alpha = 0.2, color = "grey", size = 0.1), dpi = 300) +
    geom_smooth(aes(group = transformation, color = highlight), method = "lm", size = 0.6, se = FALSE) +
    geom_rug(data = time_minor_ticks, aes(y = ticks, x = 0), sides = "l", color = "black", length = unit(0.3, "mm")) +
    geom_rug(data = time_major_ticks, aes(y = ticks, x = 0), sides = "l", color = "black", length = unit(0.5, "mm")) +
    annotation_logticks(sides = "b", short = unit(0.3, "mm"), mid = unit(0.3, "mm"), long = unit(0.5, "mm")) +
    scale_y_log10(breaks = c(0.001, 1, 60, 60 * 60, 24 * 60 * 60, 7 * 24 * 60 * 60),
        labels = c("1ms", "1sec", "1min", "1hour", "1day", "1week"), name = "", limits = c(1, NA), expand = expansion(mult = 0.01, 0.05)) +
    scale_x_log10(breaks = c(300, 1000, 3000, 1e4, 3e4)) +
    # scale_color_manual(values = transformation_category_colors, labels = transformation_category_pretty, guide = "none") +
    labs(title = "(F) The computation time depends on \\#cells", x = "\\#Cells") +
    theme(plot.title.position = "plot")

scaling_plot <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  filter(pca_dim == 10) %>%
  left_join(trans_families) %>%
  left_join(dataset_summaries %>% dplyr::select(-c(row_means, row_vars))) %>%
  ggplot(aes(x = n_cells, y = cputime_sec)) +
    ggrastr::rasterise(ggbeeswarm::geom_quasirandom(alpha = 0.2, color = "grey", size = 0.1), dpi = 300) +
    geom_smooth(aes(group = transformation, color = family), method = "lm", size = 0.6, se = FALSE) +
    geom_rug(data = time_minor_ticks, aes(y = ticks, x = 0), sides = "l", color = "black", length = unit(0.3, "mm")) +
    geom_rug(data = time_major_ticks, aes(y = ticks, x = 0), sides = "l", color = "black", length = unit(0.5, "mm")) +
    annotation_logticks(sides = "b", short = unit(0.3, "mm"), mid = unit(0.3, "mm"), long = unit(0.5, "mm")) +
    scale_y_log10(breaks = c(0.001, 1, 60, 60 * 60, 24 * 60 * 60, 7 * 24 * 60 * 60),
        labels = c("1ms", "1sec", "1min", "1hour", "1day", "1week"), name = "", limits = c(1, NA), expand = expansion(mult = 0.01, 0.05)) +
    scale_x_log10(breaks = c(300, 1000, 3000, 1e4, 3e4)) +
    scale_color_manual(values = trans_families_colors, guide = "none") +
    labs(title = "(B) The computation time depends on \\#cells", x = "\\#Cells") +
    theme(plot.title.position = "plot")

scaling_plot
```




```{r fig.height=3.71, fig.width=6.69, dev="ragg_png"}
plot_assemble(list(plot = perf_plot,          x = 0, y = 0,   width = 90, height = 60),
              list(plot = scaling_plot,       x = 0, y = 60,  width = 81, height = 40),
              annotate_text("Sanity\nDistance", fontsize = font_size_small, x = 77, y = 69),
              annotate_text("Sanity MAP", fontsize = font_size_small, x = 77, y = 71.7),
              annotate_text("GLM PCA", fontsize = font_size_small, x = 77, y = 74.5),
              list(plot = grid::linesGrob(x = c(1,0), y = c(0,1), default.units = "npc", gp = grid::gpar(col = "black", lty = 1, lwd = 0.5)), x = 76.1, y = 75, width = 0.8, height = 1),
              annotate_text("Dino", fontsize = font_size_small, x = 77, y = 77.5),
              annotate_text("...", fontsize = font_size_small, x = 80, y = 82.5, angle = 90),
              annotate_text("$\\log(x/s+1)$\n\\;$\\rightarrow$HVG", fontsize = font_size_small, x = 77, y = 89),
              width = 90, height = 100, units = "mm", show_grid_lines = FALSE,
              filename = "../output/main_duration.pdf", latex_support = TRUE)
```


```{r}
res %>%
  group_by(transformation) %>%
  summarize(cputime_year = sum(cputime_sec) / (60 * 60 * 24 * 365)) %>%
  mutate(relative = round(cputime_year / sum(cputime_year), 3),
         cputime_year = round(cputime_year, 1))
res %>%
  left_join(trans_families) %>%
  group_by(family) %>%
  summarize(cputime_year = sum(cputime_sec) / (60 * 60 * 24 * 365)) %>%
  mutate(relative = round(cputime_year / sum(cputime_year), 3),
         cputime_year = round(cputime_year, 1))
```


```{r}
res %>%
  group_by(benchmark, pca_dim, knn, dataset, replicate) %>%
  transmute(transformation, cputime_sec, logp1_time = cputime_sec[which(transformation == "logp1")[1]]) %>%
  mutate(relative = cputime_sec / logp1_time) %>%
  ungroup() %>%
  group_by(transformation) %>%
  summarize(mean = mean(relative, na.rm = TRUE), median = median(relative, na.rm = TRUE), quantile_10perc = quantile(relative, 0.1, na.rm = TRUE), quantile_90perc = quantile(relative, 0.9, na.rm = TRUE),
            quantile_25perc = quantile(relative, 0.25, na.rm = TRUE), quantile_75perc = quantile(relative, 0.75, na.rm = TRUE))
```




# Session Info

```{r}
sessionInfo()
```

