---
title: "R Notebook"
---

```{r}
library(tidyverse)
library(tidylog)
library(SingleCellExperiment)
source("utils.R")
source("annotation_helper.R")
source("../benchmark/src/consistency_benchmark/download_helper.R")
data_folder <- "../extra_data"


set.seed(1)
```

```{r}
selected_transformations <- c("raw", "logp1", "pearson_clip", "sanity_map")
```


# Make the Size Factor confounding line

```{r}
size_factor_transformation_res <- readRDS("../extra_data/svensson_2017_1_transformed.Rds")
Y <- size_factor_transformation_res$transformed_dat$raw_counts
size_factors <- colSums2(Y)
size_factors <- size_factors / mean(size_factors)
```


```{r}
size_factor_dep_data <- enframe(size_factor_transformation_res$transformed_dat, name = "transformation", value = "transformed_data") %>%
  add_row(transformation = "raw", transformed_data = list(Y)) %>%
  filter(transformation %in% selected_transformations) %>%
  mutate(pca = map2(transformation, transformed_data, function(name, dat){
   if(name == "sanity_dists") cmdscale(as.matrix(dat), k = 10)
   else irlba::prcomp_irlba(t(dat), n = 10)$x 
  })) %>%
  transmute(transformation, pca, cell_name = list(paste0("cell_", seq_len(ncol(Y))))) %>%
  unnest(c(pca, cell_name)) %>%
  left_join(tibble(cell_name = paste0("cell_", seq_len(ncol(Y))), size_factor = size_factors)) 
```


```{r}
size_factor_dep_plots <- size_factor_dep_data %>%
  mutate(transformation2 = factor(transformation, levels = c(as.character(trans_families$transformation), "raw")),
       transformation_labelled = factor(as.character(c(trans_labels, raw = "Raw")[as.character(transformation2)]), 
                                        levels = as.character(c(trans_labels, raw = "Raw")[c(levels(trans_families$transformation), "raw")]))) %>% 
  left_join(add_row(trans_families, transformation = "raw", family = "raw")) %>%
  mutate(family = factor(family, levels = c("raw", "delta_method", "glm_residual", "latent_expr"))) %>%
  group_by(transformation) %>%
  mutate(pca = pca * 10 / quantile(abs(pca), 0.99)) %>%
  group_by(family) %>%
  group_map(function(dat, key){
    cat <- key[[1]][1]
    ggplot(dat, aes(x = pca[,1], y = pca[,2])) +
      # geom_hline(yintercept = -11, size = 0.5) + geom_vline(xintercept = -16, size = 0.5) +
      annotate("segment", x = -16, xend = -10, y = -11, yend = -11, arrow = arrow(length = unit(0.5, "mm"))) +
      annotate("segment", x = -16, xend = -16, y = -11, yend = -5, arrow = arrow(length = unit(0.5, "mm"))) +
      annotate("text", x = -15, y = -10, label = "PCA", size = font_size_small / .pt, vjust = 0, hjust = 0) +
      geom_point(aes(color = size_factor), size = 0.7) +
      # facet_wrap(vars(transformation_labelled), ncol = 4, labeller = labeller(transformation_labelled = label_parsed)) +
      ggh4x::facet_wrap2(vars(transformation_labelled), ncol = 4, strip = ggh4x::strip_vanilla(clip = "off")) +
      coord_fixed(xlim = c(-16, 16), ylim = c(-11, 11)) +
      scale_x_continuous(expand = expansion(0)) +
      scale_y_continuous(expand = expansion(0)) +
      scale_color_viridis_c(limits = c(0.333, 3), breaks = c(0.4, 1, 2.5), oob = scales::squish, trans = "log2") +
      theme(legend.position = "bottom",
            legend.justification = "center", 
            legend.key.size = unit(font_size_small, "pt"),
            legend.title = element_text(size = font_size_small),
            axis.ticks = element_blank(), axis.text = element_blank(), axis.line = element_blank(),
            axis.title = element_blank(), plot.title = element_blank(),
            strip.text = element_blank(), strip.background = element_blank()) 
  })

size_factor_dep_plots[[1]] <- size_factor_dep_plots[[1]] +
  guides(color = guide_colorbar(title = "Size Factor", barheight = unit(3, "pt"), title.position = "top", title.theme = element_text(size = font_size_small), 
                                title.hjust = 0.5, label.theme = element_text(size = font_size_tiny))) +
  theme(legend.position = c(0.7, 0.17), legend.direction = "horizontal")
drop
size_factor_dep_plots[2:4] <- map(size_factor_dep_plots[2:4], ~ .x + guides(color =  "none"))

size_factor_dep_plots
```



# Mean variance dependence


```{r}
tenx_data_transformed <- readRDS( "../extra_data/GSE130931_transformed.Rds")
Y <- tenx_data_transformed$raw
```




```{r}
mean_var_df <- enframe(tenx_data_transformed$transformed_dat, name = "transformation", value = "transformed_data") %>%
  add_row(transformation = "raw", transformed_data = list(Y)) %>%
  filter(transformation %in% selected_transformations) %>%
  mutate(gene_measures = map2(transformed_data, transformation, function(dat, trans){
    if(trans == "sanity_dists"){
      tibble(gene_mean = rowMeans2(Y),
             gene_var = rowVars(matrix(rnorm(n = nrow(dat$mean) * ncol(dat$mean),
                                             mean = dat$mean, sd = dat$sd), 
                                       nrow = nrow(dat$mean), ncol = ncol(dat$mean))))
    }else if(str_detect(trans, "_hvg") || trans == "sctransform"){
      gene_oi <- as.integer(str_replace(rownames(dat), "Gene_", ""))
      tibble(gene_mean = rowMeans2(Y, rows = gene_oi), gene_var = rowVars(dat))
    }else{
      tibble(gene_mean = rowMeans2(Y), gene_var = rowVars(dat))
    }
  })) %>%
  dplyr::select(transformation, gene_measures) %>%
  unnest(gene_measures)
```



```{r}
library(ggh4x)

limits <- tibble(raw = 5e4, 
                 logp1 = 5,  acosh = 5, logp_alpha = 5, logp_cpm = 15, logp1_size_normed = 10, logp1_hvg = 5, logp1_zscore = 5, logp1_hvg_zscore = 5,
                 pearson_clip = 5, sctransform = 5, pearson_analytic = 5, rand_quantile = 5, pearson_clip_hvg = 5, pearson_clip_zscore = 5, pearson_clip_hvg_zscore = 5, pearson = 15,
                 sanity_map = 0.8, sanity_dists = 5, dino = 0.6, normalisr_normvar = 40) %>%
  pivot_longer(everything(), names_to = "transformation", values_to = "ceiling")

mean_var_plots <- mean_var_df %>%
  mutate(transformation2 = factor(transformation, levels = c(as.character(trans_families$transformation), "raw")),
         transformation_labelled = factor(as.character(c(trans_labels, raw = "Raw")[as.character(transformation2)]), 
                                          levels = as.character(c(trans_labels, raw = "Raw")[c(levels(trans_families$transformation), "raw")]))) %>% 
  left_join(add_row(trans_families, transformation = "raw", family = "raw")) %>%
  mutate(family = factor(family, levels = c("raw", "delta_method", "glm_residual", "latent_expr"))) %>%
  left_join(limits) %>%
  mutate(gene_var = ifelse(gene_var > ceiling, Inf, gene_var)) %>%
  group_by(family) %>%
  group_map(function(dat, key){
    cat <- key[[1]][1]
    ggplot(dat, aes(x = gene_mean, y = gene_var))+ 
      ggrastr::rasterise(geom_point(size = 0.05), dpi = 300) +
      geom_blank(aes(x = 1, y = ceiling)) +
      (if(cat == "raw") NULL
       else ggh4x::facet_wrap2(vars(transformation_labelled), ncol = 4, 
                         strip = ggh4x::strip_vanilla(clip = "off"), scales ="free_y")) +
      # scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
      #       labels = scales::trans_format("log10", scales::math_format(10^.x))) +
      scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                    minor_breaks = rep(1:9, times = 6) * 10^rep(seq(-3, 2), each = 9) ,
                    labels = scales::trans_format("log10", scales::math_format(10^.x)),
                    guide = "axis_minor") +
      scale_y_continuous(limits = c(0, NA),expand = expansion(mult = c(0, 0.05)),
                   breaks = function(x){
                      signif_dig <- 1
                      ord <- floor(log10(max(x)))
                      c(0, floor(max(x) / 10^(ord-signif_dig+1)) * 10^(ord-signif_dig+1))
                    }) +
      coord_cartesian(clip = "off") +
      labs(x = "Gene Mean (log-scale)", y = "Variance") +
      theme(strip.text = element_blank(), strip.background = element_blank(), plot.title = element_blank(),
            ggh4x.axis.ticks.length.minor = rel(0.5)) 
  })

mean_var_plots
```

# Make marker histograms

```{r}
mouse_lung_transformed_data <- readRDS( "../extra_data/mouse_lung_transformed.Rds")
Y <- mouse_lung_transformed_data$raw
```




```{r}
gene_id <- "Sftpc"
cells_of_interest <- colnames(Y)[mouse_lung_transformed_data$cell_type %in% "Type_2_pneumocytes"]
other_cells <- sample(setdiff(colnames(Y), cells_of_interest), size = length(cells_of_interest), replace = FALSE)

res <- enframe(mouse_lung_transformed_data$transformed_dat, name = "transformation", value = "transformed_data") %>%
  add_row(transformation = "raw", transformed_data = list(Y)) %>%
  filter(transformation %in% selected_transformations) %>%
  mutate(gene_expr = map2(transformed_data, transformation, function(dat, trans){
    if(trans == "sanity_dists"){
      stopifnot(all(dim(sanity_prob$mean) == dim(Y)))
      rownames(sanity_prob$mean) <- rownames(Y)
      colnames(sanity_prob$mean) <- colnames(Y)
      rownames(sanity_prob$sd) <- rownames(Y)
      colnames(sanity_prob$sd) <- colnames(Y)
      sanity_prob$mean[gene_id, c(cells_of_interest, other_cells)] + rnorm(n = length(cells_of_interest) * 2, mean = 0, sd = sanity_prob$sd[gene_id, c(cells_of_interest, other_cells)])
    }else{
      stopifnot(all(dim(dat) == dim(Y)))
      rownames(dat) <- rownames(Y)
      colnames(dat) <- colnames(Y)
      dat[gene_id, c(cells_of_interest, other_cells)]
    }
  }),
  cell_of_interest = map(transformation, ~ rep(c(TRUE, FALSE), each = length(cells_of_interest)))) %>%
  dplyr::select(transformation, gene_expr, cell_of_interest) %>%
  unnest(c(gene_expr, cell_of_interest))

mouse_lung_pl <- res %>%
  mutate(transformation2 = factor(transformation, levels = c(as.character(trans_families$transformation), "raw")),
       transformation_labelled = factor(as.character(c(trans_labels, raw = "Raw")[as.character(transformation2)]), 
                                        levels = as.character(c(trans_labels, raw = "Raw")[c(levels(trans_families$transformation), "raw")]))) %>% 
  left_join(add_row(trans_families, transformation = "raw", family = "raw")) %>%
  mutate(family = factor(family, levels = c("raw", "delta_method", "glm_residual", "latent_expr"))) %>%
  group_by(family, transformation_labelled) %>%
  group_map(function(dat, key){
    cat <- key[[2]][1]
    ggplot(dat, aes(x = gene_expr)) +
        geom_histogram(aes(fill = cell_of_interest), bins = 30, position = "identity", alpha = 0.6, show.legend = FALSE) +
        geom_blank(data = tibble(gene_expr = 0)) +
        # ggh4x::facet_wrap2(vars(transformation_labelled), ncol = 4, 
        #                  strip = ggh4x::strip_vanilla(clip = "off"), scales ="free", trim_blank = TRUE) +
        scale_y_continuous(expand = expansion(mult = c(0.015, NA)),
                           breaks = function(x){
                             signif_dig <- 1
                             ord <- floor(log10(max(x)))
                             c(0, floor(max(x) / 10^(ord-signif_dig+1)) * 10^(ord-signif_dig+1))
                           }) +
        scale_x_continuous(breaks = function(x){
           digits <- 1
           ax <- max(abs(max(x)), abs(min(x)))
           ord <- (floor(log10(ax)) - (digits-1))
           c(sign(min(x)) * (floor(abs(min(x)) / 10^ord) * 10^ord),
             max(sign(max(x)) * (floor(abs(max(x)) / 10^ord) * 10^ord), 0))
        }) +
        scale_fill_manual(values = c("FALSE"="grey", "TRUE"="#985277"),
                          labels = c("FALSE"="other cells",  "TRUE"="cells of the cell type associated with the marker gene")) +
        coord_cartesian(clip = "off") +
        labs(x = cat, y = "\\#cells") +
        theme(strip.background = element_blank(), strip.text = element_blank())
  })

mouse_lung_pl[[2]] <- cowplot::ggdraw(mouse_lung_pl[[2]]) +
  cowplot::draw_label(x = 0.6, y = 0.75, label = "Type II pneumocytes", size = font_size_small) +
  cowplot::draw_label(x = 0.43, y = 0.6, label = "Other cells", size = font_size_small) +
  cowplot::draw_line(x = c(0.7, 0.86), y = c(0.7, 0.33), size = 0.25) +
  cowplot::draw_line(x = c(0.43, 0.41), y = c(0.55, 0.33), size = 0.2) 
mouse_lung_pl
```


```{r}
n_genes <- nrow(tenx_data_transformed$transformed_dat$logp1)


header_height <- 15
title_gap <- 5
sf_panel_height <- 28
mv_panel_height <- 28
his_panel_height <- 28

plot_assemble(
  annotate_text("Raw Counts", x = 22.5, y = 2, fontsize = font_size, fontface = "bold", vjust = 1, hjust = 0.5),
  annotate_text("Delta Method", x = 22.5 + 45, y = 2, fontsize = font_size, fontface = "bold", vjust = 1, hjust = 0.5),
  annotate_text("GLM Residual", x = 22.5 + 45 * 2, y = 2, fontsize = font_size, fontface = "bold", vjust = 1, hjust = 0.5),
  annotate_text("Latent Expression", x = 22.5 + 45 * 3, y = 2, fontsize = font_size, fontface = "bold", vjust = 1, hjust = 0.5),
  annotate_text("$Y$", x = 22.5, y = 10, fontsize = font_size,  vjust = 0.5, hjust = 0.5),
  annotate_text("$\\log(Y/s+1)$", x = 22.5 + 45, y = 10, fontsize = font_size,  vjust = 0.5, hjust = 0.5),
  annotate_text("$\\frac{Y - \\mu}{\\sqrt{\\mu + \\alpha \\mu^2}}$", x = 22.5 + 45 * 2, y = 10, fontsize = font_size * 1.3,  vjust = 0.5, hjust = 0.5),
  annotate_text(r"($Y \sim \textrm{Poisson}(M)$)", x = 22.5 + 45 * 3 - 2, y = 8, fontsize = font_size, vjust = 1, hjust = 0.5),
  annotate_text(r"($M \sim \textrm{LogNormal}(\mu, \sigma^2)$)", x = 22.5 + 45 * 3 - 2 + 3.2, y = 8 + 4.5, fontsize = font_size, vjust = 0.5, hjust = 0.5),
  
  # Size factor influence on PCA
  annotate_text("(A) Confounding effect of size factors on PCA embedding of droplets encapsulating a homogeneous RNA solution", 
                x = 1, y = header_height + 2, fontsize = font_size, fontface = "bold", vjust = 1),
  list(plot = size_factor_dep_plots[[1]], x = 45 * 0, y = header_height + title_gap, width = 45, height = sf_panel_height),
  list(plot = size_factor_dep_plots[[2]], x = 45 * 1, y = header_height + title_gap, width = 45, height = sf_panel_height),
  list(plot = size_factor_dep_plots[[3]], x = 45 * 2, y = header_height + title_gap, width = 45, height = sf_panel_height),
  list(plot = size_factor_dep_plots[[4]], x = 45 * 3, y = header_height + title_gap, width = 45, height = sf_panel_height),
  # Mean Variance relation
  annotate_text(paste0("(B) Mean-variance relation for ", 
                       prettyNum(n_genes, big.mark = "\\,"), " genes of the 10X hematopoietic cell dataset"),
                x = 1, y = header_height + title_gap + sf_panel_height + 2, fontsize = font_size, fontface = "bold", vjust = 1),
  list(plot = mean_var_plots[[1]], x = 45 * 0, y = header_height + title_gap * 2 + sf_panel_height, width = 45, height = mv_panel_height),
  list(plot = mean_var_plots[[2]], x = 45 * 1, y = header_height + title_gap * 2 + sf_panel_height, width = 45, height = mv_panel_height),
  list(plot = mean_var_plots[[3]], x = 45 * 2, y = header_height + title_gap * 2 + sf_panel_height, width = 45, height = mv_panel_height),
  list(plot = mean_var_plots[[4]], x = 45 * 3, y = header_height + title_gap * 2 + sf_panel_height, width = 45, height = mv_panel_height),
  # Bimodal gene stabilization
  annotate_text(paste0("(C) Distribution of a single gene (Sftpc) with a bimodal expression pattern in lung epithelium"), 
                x = 1, y = header_height + title_gap * 2 + sf_panel_height + mv_panel_height + 2, fontsize = font_size, fontface = "bold", vjust = 1),
  list(plot = mouse_lung_pl[[1]], x = 45 * 0, y = header_height + title_gap * 3 + sf_panel_height + mv_panel_height, width = 45, height = his_panel_height),
  list(plot = mouse_lung_pl[[2]], x = 45 * 1, y = header_height + title_gap * 3 + sf_panel_height + mv_panel_height, width = 45, height = his_panel_height),
  list(plot = mouse_lung_pl[[3]], x = 45 * 2, y = header_height + title_gap * 3 + sf_panel_height + mv_panel_height, width = 45, height = his_panel_height),
  list(plot = mouse_lung_pl[[4]], x = 45 * 3, y = header_height + title_gap * 3 + sf_panel_height + mv_panel_height, width = 45, height = his_panel_height),
  width = 180, height = header_height + sf_panel_height + mv_panel_height + his_panel_height + title_gap * 3, units = "mm", show_grid_lines = FALSE,
  filename = "../output/main_concept_figure.pdf", latex_support = TRUE
)
```



```{r}
pca_plot_data <- size_factor_dep_data %>%
  mutate(pca = as_tibble(pca, .name_repair = \(.) paste0("PC_", 1:10))) %>%
  tidyr::unpack(pca)

bimodal_data <- res %>%
  left_join(trans_families) %>%
  dplyr::select(transformation, family, cell_of_interest, gene_expr) 

mean_var_data <- mean_var_df %>%
  left_join(trans_families) %>%
  dplyr::select(transformation, family, gene_mean, gene_var) 

writexl::write_xlsx(list("Size Factor Confounding" = pca_plot_data, "Mean-Variance Relation" = mean_var_data, "Bimodal Expression Pattern" = bimodal_data), path = "../output/main_concept_figure_source_data.xlsx")
```



# Session Info

```{r}
sessionInfo()
```




