---
title: "R Notebook"
---




```{r}
library(tidyverse)
library(gggroupedscale)
source("utils.R")
source("annotation_helper.R")
```



```{r}
res <- read_tsv("../benchmark/output/benchmark_results/simulation_results.tsv") %>% 
  mutate(transformation = factor(transformation, levels = trans_families$transformation))
```


```{r}
parameter_choices <- tibble(benchmark = "simulation", knn = 50, pca_dim = c(5, 10, 10, 200, 50),
         simulator = c("dyngen", "linear_walk", "muscat", "random_walk", "scDesign2"))
```


```{r}
res_main <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices) %>%
  tidylog::left_join(trans_families)

res_main
```

```{r}
res_main <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices)  %>%
  group_by(simulator, seed, knn) %>%
  mutate(rel_ARI = ARI / mean(ARI),
         rel_AMI = AMI / mean(AMI), 
         rel_NMI = NMI / mean(NMI)) %>%
  tidylog::left_join(trans_families)

make_main_plot_panel <- function(data, metric, add_group_label = FALSE){
  
  
  
  ggplot(data, aes(x = transformation, y = {{metric}}, color = family)) +
    geom_hline(yintercept = 1, size = 0.3, linetype = 2) +
    ggbeeswarm::geom_quasirandom(color = "grey", size = 0.3, alpha = 0.7) +
    stat_summary(geom = "point", position = position_dodge2(width = 0.3), fun.data = mean_cl_boot) +
    scale_x_grouped_discrete(grouping = ~ fct_rev(trans_families_labels[deframe(trans_families)[.x]]), gap_size = 1.5, 
                             labels = trans_labels, add_group_label = add_group_label, guide = if(add_group_label) guide_grouped_axis(angle = 90) else guide_axis(angle = 90)) +
    scale_y_continuous(limits = c(0.2, 1.8), breaks = c(0.5, 1, 1.5)) +
    scale_color_manual(values = trans_families_colors, labels = trans_families_labels, guide = "none") +
    theme_grouped_axis(axis.grouping.line_padding = unit(5, "pt"), axis.grouping.line_height = unit(10, "pt")) +
    theme(axis.title.x = element_blank(),  plot.title.position = "plot")
}



ari_pl <- res_main %>%
  make_main_plot_panel(rel_ARI, add_group_label = TRUE) +
  labs(y = "Rel. ARI", 
       title = "(A) Simulation: Adjusted Rand Index") +
  NULL

ami_pl <- res_main %>%
  make_main_plot_panel(rel_AMI, add_group_label = TRUE) +
  labs(y = "Rel. AMI", 
       title = "(B) Simulation: Adjusted Mututal Information") +
  NULL

ari_pl
ami_pl
```



```{r}
dat <- res %>%
  filter(alpha %in% c("TRUE", "FALSE")) %>%
  tidylog::inner_join(parameter_choices) %>%
  tidylog::left_join(trans_families) 


correl_dat <- dat %>%
  group_by(simulator) %>%
  summarize(ARI_cor = cor(mean_knn_overlap, ARI),
            AMI_cor = cor(mean_knn_overlap, AMI),
            overlap_middle = mean(range(mean_knn_overlap))) %>%
  mutate(ARI_cor_label = paste0("$r=", sprintf("%.2f", ARI_cor), "$"),
         AMI_cor_label = paste0("$r=", sprintf("%.2f", AMI_cor), "$"))


 ari_trend_pl <- dat %>%
  ggplot(aes(x = mean_knn_overlap, y = ARI)) +
    geom_vline(data = . %>% group_by(simulator) %>% summarize(mean = mean(mean_knn_overlap)), aes(xintercept = mean), size = 0.3, linetype = 2) +
    geom_hline(data = . %>% group_by(simulator) %>% summarize(mean = mean(ARI)), aes(yintercept = mean), size = 0.3, linetype = 2) +
    geom_smooth(method = "lm", color = "black", linetype = "dashed", se = FALSE) +
    geom_point(aes(color = family), size = 0.7) +
    shadowtext::geom_shadowtext(data = correl_dat, aes(label = ARI_cor_label, x = overlap_middle), y = 0.1, hjust = 0.5, vjust = 0.5, 
                                color = "black", bg.color = "white", size = font_size_small / .pt) +
    facet_wrap(vars(simulator), ncol = 3, scales = "free_x", labeller = labeller(simulator = dataset_labels)) +
    scale_y_continuous(limits= c(0, 1), breaks = c(0, 0.5, 1), expand = expansion(0)) +
    scale_x_continuous(expand = expansion(mult = 0.1)) +
    scale_color_manual(values = trans_families_colors, labels = as.character(trans_families_labels_long), name = "") +
    theme(legend.position = c(1-(1/3)/2, 0.25), legend.justification = "center",
          plot.title.position = "plot", strip.background = element_blank()) +
    labs(x = "$k$-NN Overlap", y = "Adjusted Rand Index",
         title = "(C) Adjusted Rand index vs. Mean overlap per dataset")



ami_trend_pl <- dat %>%
  ggplot(aes(x = mean_knn_overlap, y = AMI)) +
    geom_vline(data = . %>% group_by(simulator) %>% summarize(mean = mean(mean_knn_overlap)), aes(xintercept = mean), size = 0.3, linetype = 2) +
    geom_hline(data = . %>% group_by(simulator) %>% summarize(mean = mean(AMI)), aes(yintercept = mean), size = 0.3, linetype = 2) +
    geom_smooth(method = "lm", color = "black", linetype = "dashed", se = FALSE) +
    geom_point(aes(color = family), size = 0.7) +
    shadowtext::geom_shadowtext(data = correl_dat, aes(label = AMI_cor_label, x = overlap_middle), y = 0.1, hjust = 0.5, vjust = 0.5, 
                                color = "black", bg.color = "white", size = font_size_small / .pt) +
    facet_wrap(vars(simulator), ncol = 3, scales = "free_x", labeller = labeller(simulator = dataset_labels)) +
    scale_y_continuous(limits= c(0, 1), breaks = c(0, 0.5, 1), expand = expansion(0)) +
    scale_x_continuous(expand = expansion(mult = 0.1)) +
    scale_color_manual(values = trans_families_colors, labels = as.character(trans_families_labels_long), name = "") +
    theme(legend.position = c(1-(1/3)/2, 0.25), legend.justification = "center",
          plot.title.position = "plot", strip.background = element_blank()) +
    labs(x = "$k$-NN Overlap", y = "Adjusted Mutual Information",
         title = "(D) Adjusted Mutual Information vs. Mean overlap per dataset")


ari_trend_pl
ami_trend_pl
```

```{r}
plot_assemble(
  list(plot = ari_pl, x = 0,  y = 0,    width = 88, height = 60),
  list(plot = ami_pl, x = 90,  y = 0,  width = 88, height = 60),
  list(plot = ari_trend_pl, x = 0, y = 62, width = 180, height = 80),
  list(plot = ami_trend_pl, x = 0, y = 142, width = 180, height = 80),
  width = 180, height = 222, units = "mm", show_grid_lines = FALSE,
  filename = "../output/suppl-simulation_clustering_results.pdf", latex_support = TRUE
)
```


```{r}
res_main %>%
  ungroup() %>%
  dplyr::transmute(benchmark, transformation, family, dataset = simulator, replicate = seed, pca_dim, alpha, knn, n_clusters, n_clusters_counts, ARI, AMI, NMI, rel_ARI, rel_AMI, rel_NMI, mean_knn_overlap) %>%
  write_csv("../output/suppl-simulation_clustering_results_source_data.csv")
```



# Session Info

```{r}
sessionInfo()
```

