---
title: "R Notebook"
output: html_notebook
---



```{r}
library(SingleCellExperiment)
library(tidyverse)
`%|%` <- rlang::`%|%`
```


```{r}
if(! file.exists("../data/mouse_lung_single_cell.RData")){
  download.file("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE124872&format=file&file=GSE124872%5Fraw%5Fcounts%5Fsingle%5Fcell%2ERData%2Egz", "../data/mouse_lung_single_cell.RData.gz")
  R.utils::gunzip("../data/mouse_lung_single_cell.RData.gz")
}
if(! file.exists("../data/mouse_lung_single_cell_metadata.csv")){
  download.file("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE124872&format=file&file=GSE124872%5FAngelidis%5F2018%5Fmetadata%2Ecsv%2Egz", "../data/mouse_lung_single_cell_metadata.csv.gz")
  R.utils::gunzip("../data/mouse_lung_single_cell_metadata.csv.gz")
}
```


```{r}
load("../data/mouse_lung_single_cell.RData")
raw_counts
```


```{r}
metadat <- read_csv("../data/mouse_lung_single_cell_metadata.csv")
metadat
```

```{r}
col_data <- metadat %>%
  transmute(barcode = str_split_fixed(X1, ":", 3)[,3],
            mouse_id = identifier, age = grouping, cell_type = celltype) %>%
  mutate(cell_id = paste0(mouse_id, ":", barcode))

tmp <- tibble(X1 = colnames(raw_counts)) %>%
  separate(X1, c("mouse_id", "barcode"), sep = ":")

stopifnot(tmp$barcode == col_data$barcode)

colnames(raw_counts) <- col_data$cell_id
```



```{r}
colnames(raw_counts) <- col_data$cell_id
sce <- SingleCellExperiment(list(counts = raw_counts), colData = col_data)
sce
```


```{r}
total_umi <- colSums2(assay(sce, "counts"))
sce <- sce[rowSums2(assay(sce, "counts")) > 0, total_umi > median(total_umi) / 10 & total_umi < median(total_umi) * 10]
```





```{r}
qcstats <- scuttle::perCellQCMetrics(sce, 
                         subsets = list(Mito = (rowData(sce)$chromosome == "MT") %|% FALSE))
filtered <- scuttle::quickPerCellQC(qcstats, percent_subsets="subsets_Mito_percent")
```




```{r}
sce <- sce[, ! filtered$discard]
```



```{r}
sf <- colSums2(counts(sce))
sf <- sf / mean(sf)

alpha <- 0.05
```


```{r}
dim(sce)
mean_gene_expr <- rowMeans2(assay(sce))
subset_sce <- sce[rank(-mean_gene_expr) <= 100 | 
                      rownames(sce) %in% c("Sftpc", "Scgb1a1", "Ear2"), ]
dim(subset_sce)
```



```{r}
assay(subset_sce, "logp1") <- transformGamPoi::shifted_log_transform(subset_sce, pseudo_count = 1, size_factors = sf)
```

```{r}
colsums <- colSums2(counts(sce))
assay(subset_sce, "logp_cpm") <- log1p(t(t(counts(subset_sce)) / colsums * 1e6))
```


```{r}
assay(subset_sce, "logp_alpha") <- transformGamPoi::shifted_log_transform(subset_sce, overdispersion = alpha, size_factors = sf)
```


```{r}
assay(subset_sce, "acosh") <- transformGamPoi::acosh_transform(subset_sce, overdispersion = alpha, size_factors = sf)
```


```{r}
system.time(
  assay(subset_sce, "pearson") <- transformGamPoi::residual_transform(as.matrix(assay(subset_sce, "counts")), 
                                                                   size_factors = sf, overdispersion = alpha, clipping = TRUE,
                                                                   residual_type = "pearson", verbose = TRUE)
)
```

```{r}
system.time(
  assay(subset_sce, "rand_quantile") <- transformGamPoi::residual_transform(as.matrix(assay(subset_sce, "counts")), 
                                                             size_factors = sf, overdispersion = alpha,
                                                             residual_type = "randomized_quantile", verbose = TRUE)
)
```


```{r}
run_sanity <- function(x, variance_min = 0.01, variance_max = 20, n_bins = 116, n_threads = 1){
  stopifnot(is.matrix(x))
  stopifnot(all(colSums2(x) > 0))
  stopifnot(all(rowSums2(x) > 0))
  # write x to a file
  input <- tempfile(pattern = "matrix", fileext = ".tsv")
  output_dir <- file.path(tempdir(), paste0("sanity_output_", paste0(sample(letters, 7, replace = TRUE), collapse = "")))
  dir.create(output_dir)
  print(paste0("Output dir: ", output_dir))
  
  if(is.null(rownames(x))){
    rownames(x) <- paste0("Gene_", seq_len(nrow(x)))
  }
  if(is.null(colnames(x))){
    colnames(x) <- paste0("Cell_", seq_len(ncol(x)))
  }
  readr::write_tsv(tibble::as_tibble(x, rownames = "GeneID"), input)
  
  code <- system2("/Users/ahlmanne/prog/experiments/Sanity/bin/Sanity", args = c(paste0("--file ", input),
                                                                                 paste0("--destination ", output_dir),
                                                                                 paste0("--variance_min ", variance_min),
                                                                                 paste0("--variance_max ", variance_max),
                                                                                 paste0("--number_of_bins ", n_bins),
                                                                                 paste0("--n_threads ", n_threads),
                                                                                 "--extended_output true"))
  if(code != 0){
    stop("Sanity failed with status ", code)
  }
  
  
  res <- readr::read_tsv(file.path(output_dir, "log_transcription_quotients.txt"), col_types = readr::cols()) 
  mat <- as.matrix(res[,-1,drop=FALSE])
  rownames(mat) <- res[[1]]
  colnames(mat) <- colnames(res)[-1]
  
  errror_bars_df <- readr::read_tsv(file.path(output_dir, "ltq_error_bars.txt"), col_types = readr::cols()) 
  error_bars <- as.matrix(errror_bars_df[,-1,drop=FALSE])
  rownames(error_bars) <- errror_bars_df[[1]]
  colnames(error_bars) <- colnames(errror_bars_df)[-1]
  
  
  list(mean = mat, sd = error_bars, outdir = output_dir)
}

sane_res <- run_sanity(as.matrix(assay(subset_sce)))

```


```{r}
find_break <- function(x, digits = 1){
  stopifnot(length(x) == 1)
  ax <- abs(x)
  ord <- (floor(log10(ax)) - (digits-1))
  sign(x) * (floor(ax / 10^ord) * 10^ord)
}

find_break(pi)
find_break(17, digits = 3)
find_break(pi, digits = 2)
```



```{r make_plot, fig.width=12, fig.height=6}
color_map <-  c("Delta method VST" = "#022B3A", "Residual VST" = "#1F7A8C", "Sanity" = "#A3C9A8",
                "other" = "grey", "Raw Counts" = "#985277")

method_labeller <- c("logp1" = "log(x+1)", "logp_cpm" = "log(CPM+1)", "logp_alpha" = "log(x+1/(4*alpha))", "acosh" = "acosh(2*alpha*x+1)",
                   "pearson" = "Pearson~Resid.", "rand_quantile" = "Ra.~Qu.~Resid.",
                   "sanity_dist" = "Sanity~Distance", "sanity_map" = "Sanity~MAP", counts = "Raw~Counts")



make_gene_hist2 <- function(gene_id, cell_types_of_interest, show_facet_label){
  
  cells_of_interest <- subset_sce$cell_id[subset_sce$cell_type %in% cell_types_of_interest]
  other_cells <- sample(setdiff(subset_sce$cell_id, cells_of_interest), size = length(cells_of_interest), replace = FALSE)
  
  tibble(cell_id = c(cells_of_interest, other_cells),
         cell_type_oi = rep(c(TRUE, FALSE), each = length(cells_of_interest))) %>%
    mutate(counts = assay(subset_sce, "counts")[gene_id, cell_id],
           logp1 = assay(subset_sce, "logp1")[gene_id, cell_id],
           logp_cpm = assay(subset_sce, "logp_cpm")[gene_id, cell_id],
           logp_alpha = assay(subset_sce, "logp_alpha")[gene_id, cell_id],
           acosh = assay(subset_sce, "acosh")[gene_id, cell_id],
           rand_quantile = assay(subset_sce, "rand_quantile")[gene_id, cell_id],
           pearson = assay(subset_sce, "pearson")[gene_id, cell_id],
           sanity_dist = rnorm(n = length(cell_id), mean = sane_res$mean[gene_id, cell_id], sd = sane_res$sd[gene_id, cell_id]),
           sanity_map = sane_res$mean[gene_id, cell_id]
           ) %>%
    pivot_longer(c(counts, logp1, logp_cpm, logp_alpha, acosh, rand_quantile, pearson, sanity_dist, sanity_map), names_to = "transformation", values_to = "value") %>%
    mutate(transformation_label = as.factor(method_labeller[transformation])) %>%
    mutate(transformation = factor(transformation, levels  = c("counts", "logp1", "logp_cpm", "logp_alpha", "acosh", "pearson", "rand_quantile", "sanity_map", "sanity_dist"))) %>%
    mutate(transformation_label = fct_reorder(transformation_label, as.numeric(transformation))) %>%
    ggplot(aes(x = value)) +
      # geom_histogram(aes(fill = fill_color), bins = 30,  alpha = 0.8, position = "identity") +
      geom_histogram(aes(fill = cell_type_oi), bins = 30, position = "identity", alpha = 0.6) +
      geom_blank(data = tibble(value = 0), y = 0) +
      facet_wrap(vars(transformation_label), scales = "free", nrow = 1, labeller = label_parsed) +
      scale_y_continuous(expand = expansion(mult = c(0.015, NA))) +
      # scale_x_continuous(n.breaks = 2) +
      scale_x_continuous(breaks = function(x){
         digits <- 1
         ax <- max(abs(max(x)), abs(min(x)))
         ord <- (floor(log10(ax)) - (digits-1))
         c(sign(min(x)) * (floor(abs(min(x)) / 10^ord) * 10^ord),
           max(sign(max(x)) * (floor(abs(max(x)) / 10^ord) * 10^ord), 0))
      }) +
      scale_fill_manual(values = c("FALSE"="grey", "TRUE"="#985277"),
                        labels = c("FALSE"="other cells",  "TRUE"="cells of the cell type associated with the marker gene")) +
      coord_cartesian(clip = "off") +
      labs(x = "", y = gene_id) +
      cowplot::theme_cowplot() +
      theme(strip.background = element_blank(),
            strip.text = if(show_facet_label) element_text(size = 10) else element_blank(),
            axis.text.y = element_blank(), axis.ticks.y = element_blank(),
            panel.spacing.x = unit(10, "pt"),
            plot.title = element_blank(),
            plot.margin = margin(t = 0, r = 7, b = 0, l = 7, unit = "pt"),
            axis.title.x = element_blank())
}

hists <- list(make_gene_hist2(gene_id = "Sftpc", cell_types_of_interest = c("Type_2_pneumocytes"), show_facet_label = TRUE),
              make_gene_hist2(gene_id = "Scgb1a1", cell_types_of_interest = c("Club_cells", "Goblet_cells"), show_facet_label = FALSE),
              make_gene_hist2(gene_id = "Ear2", cell_types_of_interest = c("Alveolar_macrophage"), show_facet_label = FALSE))


legend <- cowplot::get_legend(hists[[1]] + theme(legend.position = "bottom") +
                                guides(fill = guide_legend(title = "", override.aes = list(size = 3, alpha = 1),
                                                           label.hjust = 0, label.theme =  element_text(size = 10),
                                                           reverse = TRUE)))

title <- cowplot::ggdraw() +
  cowplot::draw_figure_label("Marker Gene Distribution after Transformation",
                             fontface = "bold", size = 16)

cowplot::plot_grid(
  title,
  cowplot::plot_grid(plotlist = map(hists, ~ .x + theme(legend.position = "none")), nrow = 3, ncol = 1, align = "vh"),
  cowplot::plot_grid(NULL, legend, NULL,
                     nrow =1, rel_widths = c(1, 1, 1)),
  ncol = 1, rel_heights = c(0.07, 1, 0.1)
)

cowplot::save_plot("../output/ageing_mice_gene_hists.pdf", last_plot(), nrow = 3, ncol = 9, base_height = 1.5, base_asp = 0.8)
```





# Session Info

```{r}
sessionInfo()
```



